<?php
$topics = [];

// ============================================================
// TOPIC 1: ns-php-syntax
// ============================================================
$topics[] = [
    'id' => 'ns-php-syntax',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'PHP syntax is the set of rules that govern how PHP code is written and interpreted by the engine. It is the grammar of the language -- you must arrange words, symbols, and punctuation in the correct order for the computer to understand your instructions. PHP is a server-side scripting language designed for web development, meaning it runs on the server before sending HTML to the browser. It exists because building dynamic websites requires generating content programmatically rather than editing static HTML files by hand. PHP\'s syntax borrows from C, Perl, and Java, making it familiar to developers from those backgrounds.',
        '',
        '### ## The Big Picture',
        'PHP powers roughly three-quarters of websites using a server-side language, including platforms like WordPress and Wikipedia. Its syntax integrates with HTML through <code><?php ?></code> tags, making it natural for templating. Understanding variables, data types, operators, strings, and arrays is the foundation for everything from vanilla scripts to frameworks like Laravel and Symfony. PHP is forgiving via loose typing but offers strict typing when you opt in.',
        '',
        '### ## Core Ideas',
        '',
        '### Variables and Data Types',
        'Variables start with <code>$</code> and need no explicit type declaration -- PHP infers the type from the assigned value. The eight primitive types are boolean, integer, float, string, array, object, resource, and null.',
        '```php',
        '$name = "Alice";              // string - a sequence of characters',
        '$age = 30;                    // integer - a whole number without decimals',
        '$height = 5.8;                // float - a decimal number',
        '$isAdmin = true;              // boolean - true or false value',
        '$colors = ["red", "blue"];   // array - ordered collection of items',
        '```',
        '',
        '### Strings and Concatenation',
        'PHP has single and double-quoted strings. Double quotes interpret variables and escape sequences; single quotes treat everything literally. The dot operator <code>.</code> concatenates strings.',
        '```php',
        '$greeting = "Hello, $name!";  // double quotes interpolate $name to "Alice"',
        '$literal = \'Hello, $name!\';   // single quotes output $name literally',
        '$combined = "Hello " . "World"; // dot operator joins two strings together',
        '$now = "Time: " . date(\'H:i\'); // dot chains a function result with a string',
        '```',
        '',
        '### Arrays',
        'Arrays are ordered maps supporting integer and string keys. They hold mixed types and grow dynamically.',
        '```php',
        '$fruits = ["apple", "banana"];  // indexed array uses default integer keys',
        '$user = ["name" => "Alice", "age" => 30]; // associative array uses named keys',
        'echo $fruits[0];                // outputs "apple" via integer index access',
        'echo $user["name"];             // outputs "Alice" via string key access',
        '$fruits[] = "cherry";           // appends "cherry" at the next integer index',
        '```',
        '',
        '### Operators',
        'Arithmetic, comparison, logical, and assignment operators manipulate values. The difference between <code>==</code> (loose) and <code>===</code> (strict) is critical because PHP type-jugs automatically.',
        '```php',
        '$sum = 10 + 5;                  // addition operator returns 15',
        '$isEqual = (5 == "5");          // loose equality: true because values match',
        '$isIdentical = (5 === "5");     // strict equality: false because types differ',
        '$isAdult = ($age >= 18 && $age <= 120); // logical AND combines two comparisons',
        '```',
        '',
        '### ## Wiring It Together',
        'This script processes a registration form, validates input, and returns a response:',
        '```php',
        '<?php',
        '$errors = [];                          // initialize empty error message array',
        '$name = trim($_POST["name"] ?? "");    // read name from POST, trim whitespace',
        '$email = filter_var($_POST["email"] ?? "", FILTER_SANITIZE_EMAIL); // sanitize email',
        '',
        'if (strlen($name) < 2) {               // reject names shorter than 2 characters',
        '    $errors[] = "Name must be 2+ characters"; // push error onto array',
        '}',
        'if (!filter_var($email, FILTER_VALIDATE_EMAIL)) { // check email format validity',
        '    $errors[] = "Invalid email address"; // add validation error message',
        '}',
        '',
        'if (count($errors) > 0) {              // if any errors were collected',
        '    echo "<h3>Errors:</h3>";           // render error section heading',
        '    foreach ($errors as $error) {       // iterate every error in the array',
        '        echo "<p>$error</p>";          // display each error in a paragraph tag',
        '    }',
        '} else {',
        '    $welcome = "Welcome, $name!";     // interpolate name into greeting string',
        '    $domain = substr(strstr($email, "@"), 1); // extract domain substring after @',
        '    echo "<h1>$welcome</h1>";          // output welcome as heading',
        '    echo "<p>Your email domain: $domain</p>"; // show extracted domain',
        '}',
        '?>',
        '```',
        'This ties variables, arrays, string functions, conditionals, loops, and superglobals into a realistic form-processing flow.',
    ]),
    'keyPoints' => [
        'PHP is a server-side scripting language embedded in HTML via <?php ?> tags',
        'Variables start with $ and are loosely typed by default',
        'Eight primitive types: boolean, integer, float, string, array, object, resource, null',
        'Double-quoted strings interpolate variables; single-quoted strings do not',
        'Arrays are ordered maps supporting both integer and string keys',
        'Use === for strict comparison to avoid type-juggling surprises',
    ],
    'tags' => ['PHP', 'Syntax', 'Basics'],
    'readTimeMin' => 10,
];

// ============================================================
// TOPIC 2: ns-php-control-flow
// ============================================================
$topics[] = [
    'id' => 'ns-php-control-flow',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Control flow and functions are the mechanisms that let your PHP code make decisions, repeat tasks, and organize logic into reusable units. Control flow statements like <code>if</code>, <code>for</code>, and <code>switch</code> determine which code blocks execute based on conditions. Functions package a sequence of statements under a name so you can call them from anywhere without duplicating code. They exist because programs would be unmanageable without conditional logic, loops, and modular organization -- every nontrivial application needs these building blocks.',
        '',
        '### ## The Big Picture',
        'Control flow and functions form the backbone of every PHP application. Conditionals handle routing logic, input validation, and authorization. Loops process database result sets, arrays, and paginated data. Functions encapsulate everything from validation helpers to database queries. The <code>match</code> expression (PHP 8) and arrow functions provide modern alternatives to older constructs. Mastering these tools is necessary before moving to OOP, frameworks, or any advanced PHP topic.',
        '',
        '### ## Core Ideas',
        '',
        '### Conditionals: if, elseif, else',
        'PHP evaluates a boolean expression and executes the corresponding block. You can chain multiple conditions without limit.',
        '```php',
        'if ($score >= 90) {                  // first condition checked',
        '    $grade = "A";                    // executes only when score >= 90',
        '} elseif ($score >= 80) {            // checked only when first is false',
        '    $grade = "B";',
        '} else {',
        '    $grade = "F";                    // fallback when all conditions fail',
        '}',
        '```',
        '',
        '### The match Expression (PHP 8)',
        '<code>match</code> is a strict, expression-based alternative to <code>switch</code>. It returns a value and does not require break statements.',
        '```php',
        '$statusCode = 404;',
        '$message = match ($statusCode) {     // match evaluates $statusCode strictly',
        '    200 => "OK",                     // returns "OK" if statusCode === 200',
        '    404 => "Not Found",             // returns "Not Found" if statusCode === 404',
        '    default => "Unknown"            // fallback when no arm matches',
        '};                                    // match always returns a value',
        '```',
        '',
        '### Loops: foreach, for, while',
        '<code>foreach</code> iterates arrays and objects. <code>for</code> runs a known number of times. <code>while</code> runs until a condition becomes false.',
        '```php',
        'foreach ($users as $user) {          // loop over each element in $users array',
        '    echo $user["name"];              // access name key of current user',
        '}',
        'for ($i = 0; $i < 5; $i++) {        // init counter; check condition; increment',
        '    echo $i;                         // outputs 0 1 2 3 4',
        '}',
        'while ($row = $result->fetch()) {    // fetch returns false when no more rows',
        '    echo $row["title"];              // display title from current row',
        '}',
        '```',
        '',
        '### Defining Functions',
        'Functions are declared with <code>function</code>, accept typed parameters, and can declare a return type. Default parameter values make arguments optional.',
        '```php',
        'function greet(string $name): string { // parameter typed as string, returns string',
        '    return "Hello, $name!";           // returns the greeting to the caller',
        '}',
        'function add(int $a, int $b = 0): int { // $b defaults to 0 when not provided',
        '    return $a + $b;',
        '}',
        '$result = greet("Alice");             // calls function, $result = "Hello, Alice!"',
        '```',
        '',
        '### Variable Scope',
        'Variables declared outside functions are global; variables inside functions are local. The <code>global</code> keyword accesses global scope from within a function.',
        '```php',
        '$taxRate = 0.08;                      // global scope variable',
        'function calculateTax(float $price): float {',
        '    global $taxRate;                  // imports global $taxRate into function scope',
        '    return $price * $taxRate;         // uses the imported global value',
        '}',
        '```',
        '',
        '### Arrow Functions (PHP 7.4+)',
        'Arrow functions provide a concise syntax for closures that automatically capture variables from the parent scope by value.',
        '```php',
        '$multiplier = 2;',
        '$doubled = array_map(                 // applies callback to each array element',
        '    fn($n) => $n * $multiplier,       // arrow fn automatically captures $multiplier',
        '    [1, 2, 3]                         // input array',
        ');                                    // result: [2, 4, 6]',
        '```',
        '',
        '### ## Wiring It Together',
        'This script calculates order totals with tax and tiered discounts:',
        '```php',
        '<?php',
        '$taxRate = 0.08;                      // global tax rate for all calculations',
        '',
        'function applyDiscount(float $total): float { // apply tiered discount logic',
        '    if ($total > 100) {               // orders over $100 get 10 percent off',
        '        return $total * 0.9;          // multiply by 0.9 to apply discount',
        '    } elseif ($total > 50) {          // orders over $50 get 5 percent off',
        '        return $total * 0.95;         // multiply by 0.95 for discount',
        '    }',
        '    return $total;                    // no discount for orders $50 or less',
        '}',
        '',
        'function calculateTax(float $subtotal): float {',
        '    global $taxRate;                  // pull in global $taxRate variable',
        '    return $subtotal * $taxRate;      // compute tax amount',
        '}',
        '',
        '$items = [29.99, 49.99, 15.00];      // array of item prices',
        '$subtotal = 0;                        // initialize running total',
        '',
        'foreach ($items as $price) {          // iterate every item price',
        '    $subtotal += $price;              // accumulate into subtotal',
        '}',
        '',
        '$afterDiscount = applyDiscount($subtotal); // compute discounted amount',
        '$tax = calculateTax($afterDiscount);  // compute tax on discounted total',
        '$grandTotal = $afterDiscount + $tax;  // final amount the customer pays',
        '',
        'echo "Subtotal: \$$subtotal\\n";       // display subtotal before discount',
        'echo "After discount: \$$afterDiscount\\n"; // show discounted amount',
        'echo "Tax: \$$tax\\n";                 // show computed tax',
        'echo "Total: \$$grandTotal\\n";        // show final total',
        '?>',
        '```',
        'This example combines conditionals (tiered discount), loops (price iteration), functions with scope (tax/discount), and string interpolation in a practical order-processing scenario.',
    ]),
    'keyPoints' => [
        'if/elseif/else evaluates conditions top-down and executes the first true block',
        'match (PHP 8+) is a strict, expression-based switch alternative',
        'foreach loops over arrays; for uses a counter; while checks a condition',
        'Functions declare typed parameters and return types for predictability',
        'Variables are function-scoped by default; use global to import outer scope',
        'Arrow functions (fn) capture outer variables automatically without use keyword',
    ],
    'tags' => ['PHP', 'Control Flow', 'Functions'],
    'readTimeMin' => 11,
];

// ============================================================
// TOPIC 3: ns-php-oop
// ============================================================
$topics[] = [
    'id' => 'ns-php-oop',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Object-Oriented Programming (OOP) in PHP organizes code around objects -- instances of classes that bundle data (properties) and behavior (methods). Think of a class as a blueprint and an object as the actual thing built from that blueprint. OOP exists because procedural code becomes hard to maintain as applications grow; encapsulation, inheritance, and polymorphism help manage complexity by grouping related logic and hiding internal details. PHP\'s OOP model is class-based and borrows from Java and C++, supporting modern features like traits, interfaces, and anonymous classes.',
        '',
        '### ## The Big Picture',
        'Modern PHP relies heavily on OOP. Laravel, Symfony, and nearly every major framework are object-oriented. Composer packages are distributed as classes following PSR-4 autoloading. Understanding OOP is essential for working with frameworks, writing testable code, and contributing to the PHP ecosystem. Concepts like dependency injection, repositories, and service containers all build on OOP fundamentals.',
        '',
        '### ## Core Ideas',
        '',
        '### Classes and Objects',
        'A <code>class</code> defines properties (variables) and methods (functions). An <code>object</code> is an instance created with <code>new</code>.',
        '```php',
        'class User {                          // class declaration defines a blueprint',
        '    public string $name;              // property with public visibility',
        '    public function greet(): string { // method that returns a string',
        '        return "Hi, {$this->name}";  // $this refers to the current instance',
        '    }',
        '}',
        '$user = new User();                   // instantiate a User object from the class',
        '$user->name = "Alice";               // set property on the object',
        '$message = $user->greet();            // call method, returns "Hi, Alice"',
        '```',
        '',
        '### Constructors and Property Promotion (PHP 8+)',
        '<code>__construct</code> runs when an object is created. Constructor property promotion combines declaration and assignment in one place.',
        '```php',
        'class Product {',
        '    public function __construct(      // constructor method runs at instantiation',
        '        public string $name,          // PHP 8 promotes $name to a property automatically',
        '        public float $price           // $price is also promoted automatically',
        '    ) {}',
        '}',
        '$product = new Product("Widget", 9.99); // pass constructor arguments',
        '```',
        '',
        '### Visibility: public, protected, private',
        'Visibility controls access to properties and methods. <code>public</code> is accessible everywhere. <code>protected</code> is accessible in the class and subclasses. <code>private</code> is accessible only within the defining class.',
        '```php',
        'class BankAccount {',
        '    private float $balance = 0;       // only this class can modify $balance',
        '    public function deposit(float $amount): void { // public method accessible anywhere',
        '        if ($amount > 0) {            // guard against negative deposits',
        '            $this->balance += $amount; // modify private property internally',
        '        }',
        '    }',
        '    public function getBalance(): float { // public getter exposes balance safely',
        '        return $this->balance;',
        '    }',
        '}',
        '```',
        '',
        '### Inheritance',
        'A class can extend another class using <code>extends</code>, inheriting its public and protected methods and properties. Override parent methods by redefining them in the child.',
        '```php',
        'class Animal {',
        '    public function speak(): string {  // base method to be overridden',
        '        return "Some sound";',
        '    }',
        '}',
        'class Dog extends Animal {            // Dog inherits from Animal',
        '    public function speak(): string {  // overrides the parent speak method',
        '        return "Woof";',
        '    }',
        '}',
        '$dog = new Dog();',
        'echo $dog->speak();                   // outputs "Woof" using the overridden method',
        '```',
        '',
        '### Abstract Classes and Interfaces',
        'Abstract classes cannot be instantiated and may contain abstract methods that subclasses must implement. Interfaces declare method signatures without implementation; a class can implement multiple interfaces.',
        '```php',
        'interface Loggable {                   // contract defining required methods',
        '    public function log(string $message): void; // signature only, no body',
        '}',
        'class FileLogger implements Loggable { // must implement all interface methods',
        '    public function log(string $message): void {',
        '        file_put_contents("log.txt", $message); // actual implementation',
        '    }',
        '}',
        '```',
        '',
        '### Traits',
        'Traits are reusable code snippets that classes can import with <code>use</code>, solving PHP\'s single-inheritance limitation.',
        '```php',
        'trait Timestampable {                 // trait groups reusable behavior',
        '    public function getCreatedAt(): string {',
        '        return date("Y-m-d H:i:s");   // returns current timestamp as string',
        '    }',
        '}',
        'class Post {',
        '    use Timestampable;                 // imports all methods from the trait',
        '}',
        '$post = new Post();',
        'echo $post->getCreatedAt();           // outputs current date and time',
        '```',
        '',
        '### Static Methods and Properties',
        'Static members belong to the class itself, not to instances. Access them with <code>::</code> (Scope Resolution Operator).',
        '```php',
        'class MathHelper {',
        '    public static function square(int $n): int { // static method on class level',
        '        return $n * $n;',
        '    }',
        '}',
        'echo MathHelper::square(5);           // calls static method without instantiation',
        '```',
        '',
        '### ## Wiring It Together',
        'A polymorphic notification system using interfaces and inheritance:',
        '```php',
        '<?php',
        'interface Notifiable {                 // contract for all notification types',
        '    public function send(string $message): bool; // every notifier must implement send',
        '}',
        '',
        'class EmailNotifier implements Notifiable {',
        '    public function send(string $message): bool {',
        '        // mail($this->address, "Subject", $message); actual send logic',
        '        return true;                   // pretend email was sent successfully',
        '    }',
        '}',
        '',
        'class SmsNotifier implements Notifiable {',
        '    public function send(string $message): bool {',
        '        // sms_api::send($this->phone, $message); actual SMS logic',
        '        return true;                   // pretend SMS was sent successfully',
        '    }',
        '}',
        '',
        'class NotificationService {',
        '    public function sendAll(array $notifiers, string $message): void {',
        '        foreach ($notifiers as $notifier) { // iterate each notifier object',
        '            if ($notifier instanceof Notifiable) { // type safety check via interface',
        '                $notifier->send($message); // polymorphic call -- each class behaves differently',
        '            }',
        '        }',
        '    }',
        '}',
        '',
        '$service = new NotificationService();',
        '$service->sendAll(',
        '    [new EmailNotifier(), new SmsNotifier()], // heterogeneous array of notifiers',
        '    "System maintenance at midnight"    // message sent via each channel',
        ');',
        '?>',
        '```',
        'This demonstrates interfaces (contract), polymorphism (different send behaviors), type safety (instanceof check), and the foreach loop unifying heterogeneous notifiers.',
    ]),
    'keyPoints' => [
        'A class is a blueprint; an object is an instance created with new',
        'Visibility controls: public (anywhere), protected (class + subclasses), private (class only)',
        'Inheritance with extends allows child classes to reuse and override parent behavior',
        'Interfaces define contracts; a class can implement multiple interfaces',
        'Traits provide horizontal code reuse to work around single inheritance',
        'Static members belong to the class itself, accessed with ::',
    ],
    'tags' => ['PHP', 'OOP', 'Classes'],
    'readTimeMin' => 12,
];

// ============================================================
// TOPIC 4: ns-php-composer
// ============================================================
$topics[] = [
    'id' => 'ns-php-composer',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Composer is the dependency manager for PHP. It handles installing, updating, and autoloading third-party packages so you don\'t have to manually download libraries or write complex require statements. Think of it as npm for JavaScript or pip for Python -- it reads a <code>composer.json</code> file describing your project\'s dependencies, resolves compatible versions, and downloads them into a <code>vendor/</code> directory. Composer exists because manually managing libraries and their versions across projects is error-prone and time-consuming; a standardized tool eliminates dependency hell.',
        '',
        '### ## The Big Picture',
        'Composer is the backbone of the modern PHP ecosystem. Every major framework (Laravel, Symfony, CakePHP) and thousands of libraries are distributed through Packagist, the default Composer repository. Composer\'s autoloader (PSR-4 and PSR-0) eliminates manual require/include calls. The lock file (<code>composer.lock</code>) ensures every developer and deployment uses identical versions. CI/CD pipelines run <code>composer install --no-dev</code> to exclude development tools from production.',
        '',
        '### ## Core Ideas',
        '',
        '### composer.json Structure',
        'The <code>composer.json</code> file defines the project name, dependencies, autoloading rules, and scripts. The <code>require</code> section lists runtime packages; <code>require-dev</code> lists development-only packages.',
        '```json',
        '{',
        '    "require": {',
        '        "laravel/framework": "^10.0"  // any 10.x version compatible with semver',
        '    },',
        '    "require-dev": {',
        '        "phpunit/phpunit": "^10.0"    // only needed during development/testing',
        '    }',
        '}',
        '```',
        '',
        '### Installing Packages',
        '<code>composer install</code> reads <code>composer.lock</code> (or <code>composer.json</code> if no lock exists) and downloads exact versions. <code>composer require</code> adds a package and updates both files.',
        '```bash',
        'composer require guzzlehttp/guzzle    # adds Guzzle HTTP client to require section',
        'composer require --dev phpstan/phpstan # adds PHPStan as a dev-only dependency',
        'composer install                      # downloads all packages from lock file',
        '```',
        '',
        '### Version Constraints',
        'Composer uses semantic versioning with constraints: <code>^</code> (compatible with major), <code>~</code> (patch-level changes only), <code>>=</code> (minimum version).',
        '```json',
        '{',
        '    "require": {',
        '        "monolog/monolog": "^2.0",     // >=2.0.0, <3.0.0 (allows minor/patch bumps)',
        '        "php": ">=8.1",               // requires PHP 8.1 or higher',
        '        "package/foo": "~2.3.0"       // >=2.3.0, <2.4.0 (only patch changes)',
        '    }',
        '}',
        '```',
        '',
        '### Autoloading (PSR-4)',
        'The <code>autoload</code> section maps namespaces to directories. PSR-4 maps a namespace prefix to a directory, so <code>App\\User</code> loads from <code>src/User.php</code>.',
        '```json',
        '{',
        '    "autoload": {',
        '        "psr-4": {',
        '            "App\\\\": "src/"            // namespace App\\ points to src/ directory',
        '        }',
        '    },',
        '    "autoload-dev": {',
        '        "psr-4": {',
        '            "Tests\\\\": "tests/"         // namespace Tests\\ points to tests/ directory',
        '        }',
        '    }',
        '}',
        '```',
        'After defining, run <code>composer dump-autoload</code> to regenerate the autoloader files.',
        '',
        '### Composer Scripts',
        'Scripts run automatically at lifecycle events like <code>post-install-cmd</code> or <code>post-update-cmd</code>. Useful for clearing caches or running migrations after install.',
        '```json',
        '{',
        '    "scripts": {',
        '        "post-install-cmd": [          // runs after composer install completes',
        '            "php artisan cache:clear"   // clears Laravel cache automatically',
        '        ],',
        '        "test": "phpunit"             // custom script: composer test runs phpunit',
        '    }',
        '}',
        '```',
        '',
        '### The Vendor Directory and Autoloader',
        'After installation, packages live in <code>vendor/</code>. A single <code>require \'vendor/autoload.php\'</code> in your entry point makes every class available without manual requires.',
        '```php',
        'require __DIR__ . \'/vendor/autoload.php\'; // loads Composer\'s autoloader',
        '',
        'use GuzzleHttp\\Client;                   // import class from installed package',
        '$client = new Client();                   // instantiate without manual require',
        '$response = $client->get(\'https://api.github.com\'); // use package functionality',
        '```',
        '',
        '### ## Wiring It Together',
        'A complete project setup with autoloading and a logging dependency:',
        '```json',
        '// composer.json',
        '{',
        '    "name": "acme/blog",',
        '    "require": {',
        '        "monolog/monolog": "^3.0"       // logging library constraint',
        '    },',
        '    "autoload": {',
        '        "psr-4": {',
        '            "Acme\\\\": "src/"            // all Acme classes under src/',
        '        }',
        '    },',
        '    "scripts": {',
        '        "post-install-cmd": [',
        '            "@php -r \'echo \\"Ready\\";\'" // placeholder post-install script',
        '        ]',
        '    }',
        '}',
        '```',
        '```php',
        '// src/Logger.php',
        'namespace Acme;                          // namespace matches PSR-4 mapping',
        '',
        'use Monolog\\Level;                       // import Monolog severity levels',
        'use Monolog\\Handler\\StreamHandler;       // import handler for file output',
        '',
        'class Logger {',
        '    private \\Monolog\\Logger $logger;    // property for Monolog instance',
        '',
        '    public function __construct() {',
        '        $this->logger = new \\Monolog\\Logger(\'app\'); // create named logger',
        '        $this->logger->pushHandler(      // attach handler to write logs',
        '            new StreamHandler(\'app.log\', Level::Debug) // write debug+ to file',
        '        );',
        '    }',
        '',
        '    public function info(string $msg): void { // convenience wrapper method',
        '        $this->logger->info($msg);        // delegate to Monolog\'s info method',
        '    }',
        '}',
        '```',
        '```php',
        '// public/index.php',
        'require __DIR__ . \'/../vendor/autoload.php\'; // single autoload include',
        '',
        'use Acme\\Logger;                        // our class autoloaded via PSR-4',
        '',
        '$logger = new Logger();',
        '$logger->info("Application started");   // writes to app.log via Monolog dependency',
        '',
        'echo "Hello, world!";',
        '```',
        'This shows the full Composer workflow: defining dependencies and autoloading in composer.json, installing via CLI, and using both third-party and custom classes through the autoloader.',
    ]),
    'keyPoints' => [
        'Composer is PHP\'s dependency manager; packages come from Packagist',
        'composer.json defines dependencies; composer.lock pins exact versions',
        '^ prefix means compatible with major version; ~ means patch-level only',
        'PSR-4 autoloading maps namespaces to directories; run dump-autoload after changes',
        'require-dev adds packages only for development/testing',
        'require \'vendor/autoload.php\' is the single entry point for all classes',
    ],
    'tags' => ['PHP', 'Composer', 'Packages'],
    'readTimeMin' => 12,
];

// ============================================================
// TOPIC 5: ns-php-laravel-mvc
// ============================================================
$topics[] = [
    'id' => 'ns-php-laravel-mvc',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Laravel MVC is an architectural pattern that separates an application into three interconnected components: Models (data logic), Views (presentation), and Controllers (request handling). Laravel implements this pattern with a clean routing layer, Blade templating engine, and Eloquent ORM. MVC exists because mixing database queries, business logic, and HTML templates in a single file leads to unmaintainable spaghetti code -- separating concerns lets you change one part without breaking others. Laravel adds a service container, middleware, and Artisan CLI on top of the classic MVC pattern.',
        '',
        '### ## The Big Picture',
        'Laravel is the most popular PHP framework, and MVC is its architectural foundation. Every HTTP request follows a lifecycle: route -> middleware -> controller -> (model interaction) -> view response. Understanding this flow is essential for building Laravel applications. The framework extends MVC with features like dependency injection (service container), Eloquent for the model layer, and Blade for the view layer. Once you understand Laravel\'s MVC, you can navigate any Laravel project structure.',
        '',
        '### ## Core Ideas',
        '',
        '### Routing',
        'Routes map HTTP methods and URLs to controller methods. They are defined in <code>routes/web.php</code> (browser routes with session state) or <code>routes/api.php</code> (stateless API routes).',
        '```php',
        '// routes/web.php',
        'use App\\Http\\Controllers\\PostController;',
        '',
        'Route::get(\'/\', function () {          // GET / returns a closure response',
        '    return view(\'welcome\');             // renders resources/views/welcome.blade.php',
        '});',
        '',
        'Route::get(\'/posts\', [PostController::class, \'index\']); // GET /posts calls PostController@index',
        'Route::post(\'/posts\', [PostController::class, \'store\']); // POST /posts calls PostController@store',
        '```',
        '',
        '### Controllers',
        'Controllers group related request-handling logic into classes. They receive request data, interact with models, and return responses. Artisan generates controllers with <code>php artisan make:controller</code>.',
        '```php',
        'namespace App\\Http\\Controllers;',
        '',
        'use App\\Models\\Post;',
        'use Illuminate\\Http\\Request;',
        '',
        'class PostController extends Controller {',
        '    public function index() {          // handle GET /posts',
        '        $posts = Post::all();           // fetch all posts from database via Eloquent',
        '        return view(\'posts.index\', compact(\'posts\')); // render view with posts data',
        '    }',
        '',
        '    public function store(Request $request) { // handle POST /posts',
        '        $post = Post::create(           // create a new Post record in database',
        '            $request->validate([        // validate incoming request data',
        '                \'title\' => \'required|max:255\', // title must be present, max 255 chars',
        '                \'body\' => \'required\',    // body field is mandatory',
        '            ])',
        '        );',
        '        return redirect(\'/posts/\' . $post->id); // redirect to the new post\'s page',
        '    }',
        '}',
        '```',
        '',
        '### Blade Templates',
        'Blade is Laravel\'s templating engine. It compiles to plain PHP and provides control structures, layout inheritance, and component syntax with <code>@</code> directives.',
        '```php',
        '<!-- resources/views/layouts/app.blade.php -->',
        '<!DOCTYPE html>',
        '<html>',
        '<head>',
        '    <title>@yield(\'title\', \'Default\')</title> <!-- section yield with default -->',
        '</head>',
        '<body>',
        '    @yield(\'content\')                    <!-- child templates fill this section -->',
        '</body>',
        '</html>',
        '```',
        '```php',
        '<!-- resources/views/posts/index.blade.php -->',
        '@extends(\'layouts.app\')                  <!-- inherit from the app layout -->',
        '',
        '@section(\'title\', \'All Posts\')           <!-- set the title section -->',
        '',
        '@section(\'content\')                      <!-- define content for the layout -->',
        '    @foreach ($posts as $post)           <!-- Blade loop directive -->',
        '        <h2>{{ $post->title }}</h2>      <!-- escaped output using double curly braces -->',
        '        <p>{{ $post->excerpt }}</p>      <!-- display truncated post body -->',
        '    @endforeach',
        '@endsection                                  <!-- end the content section -->',
        '```',
        '',
        '### The Request Lifecycle',
        'Every request flows through: <code>public/index.php</code> -> HTTP kernel -> middleware stack -> router -> controller -> response. The service container resolves dependencies automatically.',
        '```php',
        '// The entry point all requests hit',
        '// public/index.php',
        '$app = require __DIR__ . \'/../bootstrap/app.php\'; // bootstrap Laravel application',
        '$kernel = $app->make(Kernel::class);    // resolve HTTP kernel from container',
        '$response = $kernel->handle(            // process the incoming request',
        '    Illuminate\\Http\\Request::capture()  // capture the HTTP request',
        ')->send();                               // send response back to browser',
        '$kernel->terminate($request, $response); // run any termination middleware',
        '```',
        '',
        '### Service Container',
        'The service container manages class dependencies and performs dependency injection. You bind interfaces to implementations and the container resolves them automatically.',
        '```php',
        '// AppServiceProvider.php',
        'use App\\Contracts\\PaymentGateway;',
        'use App\\Services\\StripeGateway;',
        '',
        'public function register(): void {',
        '    $this->app->bind(PaymentGateway::class, StripeGateway::class); // bind interface to concrete',
        '}',
        '',
        '// Controller -- container injects the bound implementation automatically',
        'public function __construct(',
        '    private PaymentGateway $gateway    // container resolves StripeGateway here',
        ') {}',
        '```',
        '',
        '### ## Wiring It Together',
        'A blog feature with route, controller, model, and view:',
        '```php',
        '// routes/web.php',
        'use App\\Http\\Controllers\\PostController;',
        '',
        'Route::resource(\'/posts\', PostController::class); // generates all RESTful routes automatically',
        '```',
        '```php',
        '// app/Models/Post.php',
        'namespace App\\Models;',
        '',
        'use Illuminate\\Database\\Eloquent\\Model;',
        '',
        'class Post extends Model {               // Eloquent model for posts table',
        '    protected $fillable = [\'title\', \'body\']; // allow mass assignment for these fields',
        '}',
        '```',
        '```php',
        '// app/Http/Controllers/PostController.php',
        'namespace App\\Http\\Controllers;',
        '',
        'use App\\Models\\Post;',
        'use Illuminate\\Http\\Request;',
        '',
        'class PostController extends Controller {',
        '    public function index() {',
        '        $posts = Post::latest()->get();  // fetch posts ordered by newest first',
        '        return view(\'posts.index\', compact(\'posts\')); // pass posts to view',
        '    }',
        '',
        '    public function show(string $id) {',
        '        $post = Post::findOrFail($id);   // find by ID or throw 404',
        '        return view(\'posts.show\', compact(\'post\')); // render single post view',
        '    }',
        '}',
        '```',
        '```php',
        '<!-- resources/views/posts/index.blade.php -->',
        '@extends(\'layouts.app\')',
        '',
        '@section(\'content\')',
        '    <h1>Blog Posts</h1>',
        '    @forelse ($posts as $post)           <!-- Blade: loop or run empty handler -->',
        '        <article>',
        '            <h2>{{ $post->title }}</h2>  <!-- escaped output of post title -->',
        '            <p>{{ Str::limit($post->body, 150) }}</p> <!-- truncated body with 150 chars -->',
        '            <a href="/posts/{{ $post->id }}">Read more</a>',
        '        </article>',
        '    @empty',
        '        <p>No posts yet.</p>             <!-- shown when posts collection is empty -->',
        '    @endforelse',
        '@endsection',
        '```',
        'This demonstrates the full MVC cycle: a request hits a route, the controller fetches data from the model, passes it to a Blade view, and the view extends a layout to render the HTML response.',
    ]),
    'keyPoints' => [
        'Laravel MVC separates concerns: Model (data), View (presentation), Controller (logic)',
        'Routes defined in web.php or api.php map URLs to controller methods',
        'Blade uses @ directives for control structures and layout inheritance',
        'The service container resolves class dependencies automatically',
        'Resource routes generate all CRUD routes with a single declaration',
        'The request flows: index.php -> kernel -> middleware -> router -> controller -> response',
    ],
    'tags' => ['PHP', 'Laravel', 'MVC'],
    'readTimeMin' => 13,
];

// ============================================================
// TOPIC 6: ns-php-eloquent
// ============================================================
$topics[] = [
    'id' => 'ns-php-eloquent',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Eloquent is Laravel\'s built-in ORM (Object-Relational Mapper) that lets you interact with your database using PHP objects instead of writing raw SQL. Each database table has a corresponding Model class that wraps the table rows into objects with methods for querying, inserting, updating, and deleting. Migrations are version-controlled PHP files that define and modify your database schema programmatically. Eloquent exists because raw SQL scattered across code is hard to maintain, test, and refactor -- an ORM provides a clean, expressive API and prevents SQL injection through parameter binding.',
        '',
        '### ## The Big Picture',
        'Eloquent is the default ORM in Laravel and follows the Active Record pattern -- each model instance corresponds to a database row. Migrations allow teams to evolve the database schema collaboratively through version control. Eloquent relationships (one-to-one, one-to-many, many-to-many) handle complex JOIN queries automatically. Combined with factories and seeders, Eloquent makes testing and prototyping fast. Understanding Eloquent is essential for any Laravel developer, as nearly every application involves database persistence.',
        '',
        '### ## Core Ideas',
        '',
        '### Migrations',
        'Migrations are PHP classes in <code>database/migrations/</code> that define table schemas. The <code>up</code> method applies changes; <code>down</code> reverses them. Run <code>php artisan make:migration</code> to generate one.',
        '```php',
        'use Illuminate\\Database\\Schema\\Blueprint;',
        'use Illuminate\\Support\\Facades\\Schema;',
        '',
        'return new class extends Migration {',
        '    public function up(): void {',
        '        Schema::create(\'posts\', function (Blueprint $table) { // create posts table',
        '            $table->id();                // auto-incrementing primary key',
        '            $table->string(\'title\');     // VARCHAR column for title',
        '            $table->text(\'body\');        // TEXT column for body content',
        '            $table->foreignId(\'user_id\')->constrained(); // foreign key to users table',
        '            $table->timestamps();        // created_at and updated_at columns',
        '        });',
        '    }',
        '',
        '    public function down(): void {',
        '        Schema::dropIfExists(\'posts\');   // reverse: drop the posts table',
        '    }',
        '};',
        '```',
        '',
        '### Models',
        'A model represents a database table. By convention, the <code>Post</code> model maps to the <code>posts</code> table. Models provide query methods, relationships, and accessors/mutators.',
        '```php',
        'namespace App\\Models;',
        '',
        'use Illuminate\\Database\\Eloquent\\Model;',
        'use Illuminate\\Database\\Eloquent\\Relations\\BelongsTo;',
        '',
        'class Post extends Model {',
        '    protected $fillable = [\'title\', \'body\', \'user_id\']; // mass-assignable fields',
        '',
        '    public function user(): BelongsTo {  // define inverse one-to-many relationship',
        '        return $this->belongsTo(User::class); // each post belongs to one user',
        '    }',
        '}',
        '```',
        '',
        '### CRUD Operations',
        'Eloquent provides methods for create, read, update, and delete without writing SQL. The query builder returns collections or model instances.',
        '```php',
        '$post = new Post();                      // create a new model instance',
        '$post->title = "My First Post";          // set the title attribute',
        '$post->body = "Hello world";            // set the body attribute',
        '$post->save();                           // INSERT the record into the database',
        '',
        '$posts = Post::where(\'user_id\', 1)       // query builder: filter by user_id',
        '              ->orderBy(\'created_at\', \'desc\') // order by newest first',
        '              ->get();                   // execute query, return Collection of models',
        '',
        '$post = Post::findOrFail(1);             // find by primary key or throw 404',
        '$post->update([\'title\' => \'Updated\']);   // UPDATE the title column',
        '',
        '$post->delete();                         // DELETE the record from the database',
        '```',
        '',
        '### Relationships',
        'Eloquent relationships define how models connect. <code>hasMany</code> / <code>belongsTo</code> handle one-to-many; <code>belongsToMany</code> handles many-to-many with pivot tables.',
        '```php',
        'class User extends Model {',
        '    public function posts(): HasMany {   // a user has many posts',
        '        return $this->hasMany(Post::class); // defines one-to-many relationship',
        '    }',
        '',
        '    public function roles(): BelongsToMany { // a user has many roles (many-to-many)',
        '        return $this->belongsToMany(Role::class); // uses role_user pivot table',
        '    }',
        '}',
        '',
        '// Usage: eager loading prevents N+1 query problem',
        '$users = User::with(\'posts\', \'roles\')->get(); // eager loads both relationships',
        'foreach ($users as $user) {              // iterate all users',
        '    foreach ($user->posts as $post) {    // access related posts without extra queries',
        '        echo $post->title;',
        '    }',
        '}',
        '```',
        '',
        '### Collections',
        'Eloquent returns results as <code>Collection</code> objects, which provide map, filter, pluck, and other functional methods beyond plain arrays.',
        '```php',
        '$posts = Post::all();                    // fetch all posts as a Collection',
        '$titles = $posts->pluck(\'title\');        // extract all titles into a new Collection',
        '$filtered = $posts->filter(fn($p) => strlen($p->title) > 10); // keep posts with long titles',
        '$first = $posts->firstWhere(\'user_id\', 1); // first post matching condition',
        '```',
        '',
        '### Accessors and Mutators',
        'Accessors format attribute values when reading; mutators transform them when setting. Defined using <code>Attribute</code> return type in PHP 8+ style.',
        '```php',
        'use Illuminate\\Database\\Eloquent\\Casts\\Attribute;',
        '',
        'class Post extends Model {',
        '    protected function excerpt(): Attribute { // define an accessor called "excerpt"',
        '        return Attribute::make(',
        '            get: fn() => substr($this->body, 0, 100) . \'...\', // truncate body to 100 chars',
        '        );',
        '    }',
        '}',
        '',
        'echo $post->excerpt;                     // accesses the computed attribute, not a column',
        '```',
        '',
        '### ## Wiring It Together',
        'A complete blog query with filtering, relationship eager loading, and collection manipulation:',
        '```php',
        '<?php',
        'namespace App\\Http\\Controllers;',
        '',
        'use App\\Models\\User;',
        'use App\\Models\\Post;',
        'use Illuminate\\Http\\Request;',
        '',
        'class BlogController extends Controller {',
        '    public function authorPosts(Request $request, string $userId) {',
        '        $user = User::with(\'posts\')       // eager load posts to avoid N+1 queries',
        '                    ->findOrFail($userId); // find user or return 404',
        '',
        '        $posts = $user->posts()           // query builder for user\'s posts',
        '                    ->where(\'published\', true) // only published posts',
        '                    ->orderBy(\'created_at\', \'desc\') // newest first',
        '                    ->get();              // execute and return Collection',
        '',
        '        $summary = [                       // build structured response',
        '            \'author\' => $user->name,       // user\'s display name',
        '            \'total\' => $posts->count(),    // count of published posts',
        '            \'recent_titles\' => $posts->take(5)->pluck(\'title\'), // titles of 5 most recent',
        '            \'has_long_posts\' => $posts->contains(fn($p) => strlen($p->body) > 1000), // any long posts?',
        '        ];',
        '',
        '        return response()->json($summary); // return JSON response',
        '    }',
        '}',
        '',
        '// Example migration for the posts table',
        '// database/migrations/xxxx_create_posts_table.php',
        'use Illuminate\\Database\\Migrations\\Migration;',
        'use Illuminate\\Database\\Schema\\Blueprint;',
        'use Illuminate\\Support\\Facades\\Schema;',
        '',
        'return new class extends Migration {',
        '    public function up(): void {',
        '        Schema::create(\'posts\', function (Blueprint $table) {',
        '            $table->id();',
        '            $table->string(\'title\', 255);',
        '            $table->longText(\'body\');',
        '            $table->boolean(\'published\')->default(false);',
        '            $table->foreignId(\'user_id\')->constrained()->cascadeOnDelete();',
        '            $table->timestamps();',
        '        });',
        '    }',
        '',
        '    public function down(): void {',
        '        Schema::dropIfExists(\'posts\');',
        '    }',
        '};',
        '```',
        'This ties migrations (schema definition), models (Post, User), relationships (belongsTo, hasMany), query builder (where, orderBy, get), eager loading (with), and collection methods (count, take, pluck, contains) into a single feature.',
    ]),
    'keyPoints' => [
        'Eloquent is Laravel\'s Active Record ORM; each model maps to a database table',
        'Migrations version-control your database schema; run php artisan migrate',
        'CRUD: create, save/update, delete, and query with where/get/find',
        'Relationships (hasMany, belongsTo, belongsToMany) handle JOINs automatically',
        'Eager loading with with() prevents the N+1 query problem',
        'Collections provide map, filter, pluck, and other functional methods on result sets',
    ],
    'tags' => ['PHP', 'Laravel', 'Eloquent', 'ORM'],
    'readTimeMin' => 13,
];

// ============================================================
// TOPIC 7: ns-php-middleware
// ============================================================
$topics[] = [
    'id' => 'ns-php-middleware',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Middleware is a layer of code that sits between an incoming HTTP request and your application\'s response, running before the controller handles the request or after the response is generated. Think of it as an onion skin around your application -- each middleware can inspect, modify, or reject requests before they reach the core logic. Middleware exists because cross-cutting concerns like authentication, logging, CORS, and rate limiting should not be duplicated in every controller; middleware centralizes these concerns in reusable, composable layers.',
        '',
        '### ## The Big Picture',
        'Laravel\'s middleware system is a pipeline that processes requests through a stack of middleware classes before reaching the route handler. Global middleware runs on every request; route middleware applies to specific routes or groups. Authentication, CSRF protection, and request logging are all implemented as middleware. Laravel ships with built-in middleware for auth, guest, throttle, and more. Custom middleware can handle anything from request transformation to IP whitelisting. Authentication builds on middleware with guards (session, token, Sanctum) and authorization via Gates and Policies.',
        '',
        '### ## Core Ideas',
        '',
        '### Creating Middleware',
        'Generate middleware with <code>php artisan make:middleware</code>. The <code>handle</code> method receives the request and a closure to pass control to the next middleware.',
        '```php',
        'namespace App\\Http\\Middleware;',
        '',
        'use Closure;',
        'use Illuminate\\Http\\Request;',
        'use Symfony\\Component\\HttpFoundation\\Response;',
        '',
        'class LogRequests {',
        '    public function handle(Request $request, Closure $next): Response {',
        '        \\Log::info(\'Request: \' . $request->method() . \' \' . $request->path()); // log method and path',
        '        $response = $next($request);     // pass request deeper into the pipeline',
        '        \\Log::info(\'Response status: \' . $response->status()); // log response status code',
        '        return $response;               // return response back up the chain',
        '    }',
        '}',
        '```',
        '',
        '### Registering Middleware',
        'Register middleware in <code>bootstrap/app.php</code> (Laravel 11+). Global middleware runs on every request; alias middleware is assigned to specific routes.',
        '```php',
        '// bootstrap/app.php (Laravel 11+)',
        'use App\\Http\\Middleware\\LogRequests;',
        'use App\\Http\\Middleware\\EnsureTokenIsValid;',
        '',
        'return Application::configure(basePath: dirname(__DIR__))',
        '    ->withMiddleware(function (Middleware $middleware) {',
        '        $middleware->append(LogRequests::class); // add to global middleware stack',
        '        $middleware->alias([',
        '            \'token.valid\' => EnsureTokenIsValid::class, // register alias for route use',
        '        ]);',
        '    })->create();',
        '',
        '// Route file using alias middleware',
        'Route::get(\'/admin\', function () {      // protected route',
        '    return view(\'admin.dashboard\');',
        '})->middleware(\'token.valid\');           // only runs with valid token',
        '```',
        '',
        '### Authentication Guards',
        'Guards define how users are authenticated per request. Laravel supports session-based, token-based, and Sanctum guards. The <code>auth</code> middleware protects routes.',
        '```php',
        '// config/auth.php (partial)',
        '\'guards\' => [',
        '    \'web\' => [                         // session-based guard for browser apps',
        '        \'driver\' => \'session\',',
        '        \'provider\' => \'users\',',
        '    ],',
        '    \'api\' => [                         // token-based guard for APIs',
        '        \'driver\' => \'sanctum\',          // uses Laravel Sanctum for API tokens',
        '        \'provider\' => \'users\',',
        '    ],',
        '],',
        '',
        '// Route protection with auth middleware',
        'Route::get(\'/dashboard\', function () {  // protected route for logged-in users',
        '    return view(\'dashboard\');',
        '})->middleware(\'auth\');                  // redirects guests to login page',
        '',
        'Route::get(\'/api/user\', function (Request $request) {',
        '    return $request->user();            // returns authenticated user via Sanctum',
        '})->middleware(\'auth:sanctum\');          // uses sanctum guard for API auth',
        '```',
        '',
        '### Gates and Policies',
        'Gates are Closure-based authorization checks; Policies are classes organizing authorization logic around a model.',
        '```php',
        '// Define a gate in AppServiceProvider',
        'use Illuminate\\Support\\Facades\\Gate;',
        '',
        'Gate::define(\'edit-post\', function (User $user, Post $post) {',
        '    return $user->id === $post->user_id; // only the author can edit',
        '});',
        '',
        '// Using the gate in a controller',
        'public function update(Request $request, Post $post) {',
        '    Gate::authorize(\'edit-post\', $post); // throws AuthorizationException if denied',
        '    $post->update($request->only(\'title\', \'body\')); // safe to update after auth',
        '}',
        '',
        '// Policy alternative (auto-discovered for Post model)',
        'class PostPolicy {',
        '    public function update(User $user, Post $post): bool {',
        '        return $user->id === $post->user_id; // same logic in policy form',
        '    }',
        '}',
        '```',
        '',
        '### Rate Limiting',
        'Laravel\'s throttle middleware limits request frequency per IP or user, preventing abuse.',
        '```php',
        '// In route definition',
        'Route::middleware(\'throttle:60,1\')->group(function () { // 60 requests per minute max',
        '    Route::get(\'/api/posts\', [PostController::class, \'index\']);',
        '    Route::post(\'/api/posts\', [PostController::class, \'store\']);',
        '});',
        '',
        '// Named rate limiter in AppServiceProvider or bootstrap/app.php',
        'RateLimiter::for(\'api\', function (Request $request) {',
        '    return Limit::perMinute(100)->by($request->user()?->id ?: $request->ip()); // 100/min per user or IP',
        '});',
        '```',
        '',
        '### ## Wiring It Together',
        'An API with logging, authentication, authorization, and rate limiting working together:',
        '```php',
        '// bootstrap/app.php (Laravel 11+)',
        'use App\\Http\\Middleware\\LogRequests;',
        'use Illuminate\\Cache\\RateLimiting\\Limit;',
        'use Illuminate\\Http\\Request;',
        'use Illuminate\\Support\\Facades\\RateLimiter;',
        '',
        'return Application::configure(basePath: dirname(__DIR__))',
        '    ->withMiddleware(function (Middleware $middleware) {',
        '        $middleware->append(LogRequests::class); // global: log every request/response',
        '        $middleware->alias([',
        '            \'check.role\' => \\App\\Http\\Middleware\\CheckRole::class, // custom role check',
        '        ]);',
        '        $middleware->api(prepend: [     // prepend to \'api\' middleware group',
        '            \\App\\Http\\Middleware\\EnsureTokenIsValid::class,',
        '        ]);',
        '    })',
        '    ->withRouting(',
        '        api: __DIR__.\'/../routes/api.php\',',
        '    );',
        '```',
        '```php',
        '// routes/api.php',
        'use App\\Http\\Controllers\\PostController;',
        '',
        'Route::middleware(\'auth:sanctum\')->group(function () {   // all routes require auth token',
        '    Route::get(\'/posts\', [PostController::class, \'index\']);',
        '    ',
        '    Route::post(\'/posts\', [PostController::class, \'store\'])',
        '        ->middleware(\'throttle:30,1\');                   // extra rate limit on writes',
        '    ',
        '    Route::put(\'/posts/{post}\', [PostController::class, \'update\'])',
        '        ->middleware(\'can:update,post\');                 // authorize via PostPolicy',
        '});',
        '```',
        '```php',
        '// app/Http/Middleware/CheckRole.php',
        'namespace App\\Http\\Middleware;',
        '',
        'use Closure;',
        'use Illuminate\\Http\\Request;',
        '',
        'class CheckRole {',
        '    public function handle(Request $request, Closure $next, string $role): mixed {',
        '        if (!$request->user() || !$request->user()->hasRole($role)) {',
        '            abort(403, \'Unauthorized\');  // reject with 403 if wrong role',
        '        }',
        '        return $next($request);          // pass through if authorized',
        '    }',
        '}',
        '```',
        '```php',
        '// app/Policies/PostPolicy.php',
        'namespace App\\Policies;',
        '',
        'use App\\Models\\User;',
        'use App\\Models\\Post;',
        '',
        'class PostPolicy {',
        '    public function update(User $user, Post $post): bool {',
        '        return $user->id === $post->user_id; // only post author can update',
        '    }',
        '',
        '    public function delete(User $user, Post $post): bool {',
        '        return $user->id === $post->user_id || $user->isAdmin(); // author or admin',
        '    }',
        '}',
        '```',
        'This demonstrates middleware pipeline composition: logging (global), token validation (api group), auth:sanctum (route group), throttle (specific routes), and policy-based authorization (can middleware).',
    ]),
    'keyPoints' => [
        'Middleware sits between request and controller; handles cross-cutting concerns',
        'Global middleware runs on all requests; alias middleware applies to specific routes',
        'Authentication guards (session, token, Sanctum) determine how users are verified',
        'Gates are Closure-based authorization; Policies are class-based per model',
        'Throttle middleware limits request rates to prevent abuse',
        'Middleware receives a request, passes it down the pipeline, and gets a response back',
    ],
    'tags' => ['PHP', 'Laravel', 'Middleware', 'Auth'],
    'readTimeMin' => 14,
];

// ============================================================
// TOPIC 8: ns-php-testing
// ============================================================
$topics[] = [
    'id' => 'ns-php-testing',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Testing in PHP means writing code that verifies your application behaves correctly. PHPUnit is the de facto standard testing framework, and Pest is a modern, expressive wrapper built on top of PHPUnit. Tests execute your application code with known inputs and assert that outputs match expectations. Testing exists because manual testing is slow, error-prone, and doesn\'t scale -- automated tests catch regressions, document behavior, and give you confidence to refactor. The testing pyramid recommends many fast unit tests, fewer integration tests, and even fewer end-to-end tests.',
        '',
        '### ## The Big Picture',
        'PHPUnit has been the backbone of PHP testing for decades. Pest offers a more readable syntax with functions like <code>it()</code>, <code>expect()</code>, and <code>toBe()</code>, while still running on PHPUnit under the hood. Laravel uses PHPUnit by default and provides helper methods for HTTP testing, database testing, and mocking. Factories generate test data, and seeders populate databases for integration tests. A solid test suite is non-negotiable for production applications -- it enables continuous delivery, documents edge cases, and prevents regressions during refactoring.',
        '',
        '### ## Core Ideas',
        '',
        '### PHPUnit Test Structure',
        'Tests are classes extending <code>PHPUnit\\Framework\\TestCase</code>. Methods prefixed with <code>test</code> or annotated with <code>#[Test]</code> are test cases. Assertions compare actual vs. expected values.',
        '```php',
        'use PHPUnit\\Framework\\TestCase;',
        '',
        'class UserTest extends TestCase {',
        '    public function test_full_name_is_constructed_from_first_and_last(): void {',
        '        $user = new \\App\\User(\'John\', \'Doe\'); // create a user instance',
        '        $this->assertEquals(\'John Doe\', $user->fullName()); // assert fullName matches',
        '    }',
        '',
        '    #[Test]',
        '    public function email_validation_rejects_invalid_formats(): void {',
        '        $validator = new \\App\\Validator();',
        '        $this->assertFalse($validator->isEmail(\'not-an-email\')); // assert returns false',
        '    }',
        '}',
        '```',
        '',
        '### Pest Syntax',
        'Pest uses functions instead of classes. The <code>test()</code> and <code>it()</code> functions define cases; <code>expect()</code> enables a fluent assertion API.',
        '```php',
        '// tests/Unit/UserTest.php',
        'test(\'full name combines first and last\', function () {',
        '    $user = new \\App\\User(\'Jane\', \'Doe\');',
        '    expect($user->fullName())->toBe(\'Jane Doe\'); // fluent assertion',
        '});',
        '',
        'it(\'validates email format correctly\', function () {',
        '    $validator = new \\App\\Validator();',
        '    expect($validator->isEmail(\'jane@example.com\'))->toBeTrue(); // passes',
        '    expect($validator->isEmail(\'bad\'))->toBeFalse(); // fails for bad input',
        '});',
        '```',
        '',
        '### Data Providers',
        'Data providers supply multiple input sets to a single test, avoiding duplication.',
        '```php',
        'use PHPUnit\\Framework\\Attributes\\DataProvider;',
        '',
        'class MathTest extends TestCase {',
        '    #[DataProvider(\'additionProvider\')]',
        '    public function test_add(int $a, int $b, int $expected): void {',
        '        $this->assertEquals($expected, \\App\\Math::add($a, $b));',
        '    }',
        '',
        '    public static function additionProvider(): array {',
        '        return [',
        '            [1, 2, 3],                 // test case: 1 + 2 = 3',
        '            [0, 0, 0],                 // test case: 0 + 0 = 0',
        '            [-1, 1, 0],               // test case: -1 + 1 = 0',
        '        ];',
        '    }',
        '}',
        '',
        '// Pest equivalent',
        'it(\'adds numbers correctly\', function (int $a, int $b, int $expected) {',
        '    expect(\\App\\Math::add($a, $b))->toBe($expected);',
        '})->with([',
        '    [1, 2, 3],',
        '    [0, 0, 0],',
        '    [-1, 1, 0],',
        ']);',
        '```',
        '',
        '### Mocking',
        'Mocks replace real objects with test doubles that simulate behavior and verify interactions.',
        '```php',
        'use PHPUnit\\Framework\\TestCase;',
        '',
        'class OrderServiceTest extends TestCase {',
        '    public function test_order_sends_notification(): void {',
        '        $mailer = $this->createMock(\\App\\Mailer::class); // create test double',
        '        $mailer->expects($this->once())  // assert method is called exactly once',
        '               ->method(\'send\')          // specify the method to mock',
        '               ->with(\'Thank you!\')      // assert argument passed to send',
        '               ->willReturn(true);       // define return value',
        '',
        '        $service = new \\App\\OrderService($mailer); // inject mock',
        '        $service->processOrder(100);     // execute with mocked dependency',
        '    }',
        '}',
        '```',
        '',
        '### Laravel HTTP Tests',
        'Laravel provides methods like <code>get()</code>, <code>post()</code>, and <code>assertStatus()</code> to test HTTP endpoints without a real server.',
        '```php',
        'namespace Tests\\Feature;',
        '',
        'use Tests\\TestCase;',
        'use App\\Models\\Post;',
        'use App\\Models\\User;',
        '',
        'class PostTest extends TestCase {',
        '    public function test_authenticated_user_can_create_post(): void {',
        '        $user = User::factory()->create(); // create a test user via factory',
        '',
        '        $response = $this->actingAs($user) // authenticate as this user',
        '                         ->post(\'/posts\', [ // send POST request to /posts',
        '                             \'title\' => \'Test Title\',',
        '                             \'body\' => \'Test body content\',',
        '                         ]);',
        '',
        '        $response->assertStatus(302);      // assert redirect after creation',
        '        $this->assertDatabaseHas(\'posts\', [ // verify database has the record',
        '            \'title\' => \'Test Title\',',
        '        ]);',
        '    }',
        '}',
        '```',
        '',
        '### SetUp and TearDown',
        'Run common setup before each test and cleanup after. Prevents duplication of test scaffolding.',
        '```php',
        'use PHPUnit\\Framework\\TestCase;',
        '',
        'class UserRepositoryTest extends TestCase {',
        '    private \\App\\UserRepository $repository;',
        '',
        '    protected function setUp(): void {    // runs before every test method',
        '        $this->repository = new \\App\\UserRepository(); // fresh instance per test',
        '    }',
        '',
        '    protected function tearDown(): void {  // runs after every test method',
        '        \\Mockery::close();                 // clean up Mockery expectations',
        '    }',
        '',
        '    public function test_find_returns_null_for_missing_user(): void {',
        '        $result = $this->repository->find(999); // non-existent ID',
        '        $this->assertNull($result);         // expect null result',
        '    }',
        '}',
        '```',
        '',
        '### ## Wiring It Together',
        'A full Laravel feature test for a blog API endpoint:',
        '```php',
        '<?php',
        'namespace Tests\\Feature;',
        '',
        'use Tests\\TestCase;',
        'use App\\Models\\User;',
        'use App\\Models\\Post;',
        'use Illuminate\\Foundation\\Testing\\RefreshDatabase;',
        '',
        'class PostApiTest extends TestCase {',
        '    use RefreshDatabase;                  // reset database after each test',
        '',
        '    public function test_unauthenticated_user_cannot_create_post(): void {',
        '        $response = $this->postJson(\'/api/posts\', [ // POST as JSON without auth',
        '            \'title\' => \'Hacked Post\',',
        '            \'body\' => \'Should not appear\',',
        '        ]);',
        '',
        '        $response->assertStatus(401);      // assert unauthorized response',
        '    }',
        '',
        '    public function test_authenticated_user_can_list_own_posts(): void {',
        '        $user = User::factory()            // use factory to create a test user',
        '            ->has(Post::factory()->count(3)) // create 3 posts for this user',
        '            ->create();',
        '',
        '        $response = $this->actingAs($user) // authenticate',
        '                         ->getJson(\'/api/posts\'); // GET request expecting JSON',
        '',
        '        $response->assertStatus(200)       // assert successful response',
        '                 ->assertJsonCount(3);     // assert response has 3 posts',
        '    }',
        '',
        '    #[\\PHPUnit\\Framework\\Attributes\\DataProvider(\'validationProvider\')]',
        '    public function test_post_validation_rules(string $field, mixed $value, string $errorKey): void {',
        '        $user = User::factory()->create();',
        '',
        '        $response = $this->actingAs($user)',
        '                         ->postJson(\'/api/posts\', [',
        '                             $field => $value,',
        '                         ]);',
        '',
        '        $response->assertStatus(422)       // assert validation error status',
        '                 ->assertJsonValidationErrors([$errorKey]); // check specific field error',
        '    }',
        '',
        '    public static function validationProvider(): array {',
        '        return [',
        '            \'title required\' => [\'title\', \'\', \'title\'],',
        '            \'title too long\' => [\'title\', str_repeat(\'a\', 256), \'title\'],',
        '            \'body required\' => [\'body\', null, \'body\'],',
        '        ];',
        '    }',
        '}',
        '```',
        'This combines PHPUnit structure, RefreshDatabase trait, Laravel HTTP test helpers (actingAs, postJson, getJson), factories with relationships, JSON assertions, and a data provider for comprehensive validation coverage.',
    ]),
    'keyPoints' => [
        'PHPUnit is the standard PHP testing framework; Pest offers a more expressive syntax on top',
        'Test methods use assertions like assertEquals, assertTrue, and assertDatabaseHas',
        'Data providers run the same test with multiple input sets',
        'Mocks replace real dependencies to verify interactions without side effects',
        'Laravel HTTP tests simulate requests in-memory with helpers like actingAs and postJson',
        'RefreshDatabase trait resets the database between tests for isolation',
    ],
    'tags' => ['PHP', 'Testing', 'PHPUnit', 'Pest'],
    'readTimeMin' => 14,
];

// ============================================================
// TOPIC 9: ns-php-wordpress
// ============================================================
$topics[] = [
    'id' => 'ns-php-wordpress',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'WordPress plugin and theme development is the practice of extending WordPress\'s functionality without modifying core files. A plugin adds custom features, while a theme controls the visual presentation. The WordPress plugin system is built on hooks -- actions (trigger points) and filters (data modifiers) -- that let your code run at specific moments during request execution. Plugin and theme development exists because directly editing WordPress core would lose changes on every update; hooks provide stable, upgrade-safe extension points that survive core upgrades.',
        '',
        '### ## The Big Picture',
        'WordPress powers roughly 40% of all websites. Its plugin architecture has created a massive ecosystem with over 60,000 free plugins. Themes use a template hierarchy that falls back from page-specific templates to <code>index.php</code>. Custom post types extend WordPress beyond blog posts into any content type (products, events, portfolios). The Loop is the central pattern for displaying content. Understanding hooks (actions and filters), the template hierarchy, the Loop, and enqueuing assets is essential for any WordPress developer building custom websites or contributing to the ecosystem.',
        '',
        '### ## Core Ideas',
        '',
        '### Plugin Structure',
        'A plugin is a PHP file with a specific header comment placed in <code>wp-content/plugins/</code>. The header identifies the plugin in the admin dashboard.',
        '```php',
        '<?php',
        '/**',
        ' * Plugin Name: Custom Quotes      // displayed name in plugins list',
        ' * Description: Adds a custom quote post type and shortcode',
        ' * Version: 1.0.0',
        ' * Author: Your Name',
        ' */',
        '',
        '// Prevent direct access',
        'if (!defined(\'ABSPATH\')) {           // ABSPATH is WordPress root directory constant',
        '    exit;                            // stop execution if accessed directly',
        '}',
        '```',
        '',
        '### Actions and Filters',
        'Actions run at specific points (e.g., <code>init</code>, <code>wp_head</code>); filters modify data (e.g., <code>the_content</code>, <code>excerpt_length</code>). Both use <code>add_action</code> and <code>add_filter</code>.',
        '```php',
        '// Action: runs code at a specific execution point',
        'add_action(\'init\', \'register_my_post_type\'); // hook function into WordPress init event',
        '',
        'function register_my_post_type(): void {',
        '    register_post_type(\'quote\', [       // register a custom post type',
        '        \'public\' => true,',
        '        \'label\' => \'Quotes\',',
        '        \'supports\' => [\'title\', \'editor\', \'thumbnail\'],',
        '    ]);',
        '}',
        '',
        '// Filter: modifies content before output',
        'add_filter(\'the_content\', \'add_quote_prefix\'); // filter post content before display',
        '',
        'function add_quote_prefix(string $content): string {',
        '    if (get_post_type() === \'quote\') {  // only modify quote post type',
        '        return \'<blockquote>\' . $content . \'</blockquote>\'; // wrap in blockquote tags',
        '    }',
        '    return $content;                    // pass through unmodified',
        '}',
        '```',
        '',
        '### Shortcodes',
        'Shortcodes are macros that expand to dynamic content. Register them with <code>add_shortcode</code>. The function returns a string that replaces the shortcode in post content.',
        '```php',
        'add_shortcode(\'random_quote\', \'render_random_quote\'); // register [random_quote] shortcode',
        '',
        'function render_random_quote(): string {',
        '    $args = [',
        '        \'post_type\' => \'quote\',        // query the quote post type',
        '        \'posts_per_page\' => 1,          // only fetch one post',
        '        \'orderby\' => \'rand\',            // randomize the order',
        '    ];',
        '    $query = new WP_Query($args);       // create custom database query',
        '',
        '    if ($query->have_posts()) {         // check if any posts were found',
        '        $query->the_post();             // set up post data for template tags',
        '        return \'<p class="quote">\' . get_the_content() . \'</p>\'; // return post content',
        '    }',
        '    return \'<p>No quotes found.</p>\';   // fallback when no posts exist',
        '}',
        '',
        '// Usage in post editor: [random_quote]',
        '```',
        '',
        '### The Loop',
        'The Loop is WordPress\'s standard way of displaying posts. It iterates through posts from a query, setting up global post data for each iteration.',
        '```php',
        '// Typically in index.php or archive.php',
        'if (have_posts()) {                     // check if query returned any posts',
        '    while (have_posts()) {              // loop while there are posts to process',
        '        the_post();                     // set up $post global with current post data',
        '        ?>',
        '        <article>',
        '            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>',
        '            <div><?php the_excerpt(); ?></div>',
        '        </article>',
        '        <?php',
        '    }',
        '} else {',
        '    echo \'<p>No posts found.</p>\';      // shown when no posts match query',
        '}',
        '```',
        '',
        '### Enqueuing Assets',
        'Use <code>wp_enqueue_script</code> and <code>wp_enqueue_style</code> to load JavaScript and CSS. Always enqueue rather than hardcode tags to avoid duplication and manage dependencies.',
        '```php',
        'add_action(\'wp_enqueue_scripts\', \'load_plugin_assets\'); // hook into frontend asset loading',
        '',
        'function load_plugin_assets(): void {',
        '    wp_enqueue_style(                  // register and enqueue a stylesheet',
        '        \'my-plugin-styles\',            // unique handle for this stylesheet',
        '        plugin_dir_url(__FILE__) . \'assets/style.css\', // full URL to CSS file',
        '        [],                            // no dependencies',
        '        \'1.0.0\'                        // version string for cache busting',
        '    );',
        '',
        '    wp_enqueue_script(                 // register and enqueue a JavaScript file',
        '        \'my-plugin-script\',            // unique handle',
        '        plugin_dir_url(__FILE__) . \'assets/script.js\', // full URL to JS file',
        '        [\'jquery\'],                    // depends on jQuery being loaded first',
        '        \'1.0.0\',                       // version',
        '        true                           // load in footer (not header)',
        '    );',
        '}',
        '```',
        '',
        '### Theme Template Hierarchy',
        'WordPress selects the appropriate template file based on the query. The hierarchy falls back from most specific to most generic (<code>index.php</code>).',
        '```php',
        '// templates in increasing specificity:',
        '// index.php          -> ultimate fallback for all requests',
        '// archive.php         -> archive pages (category, tag, date, author)',
        '// single.php          -> single post of any post type',
        '// single-quote.php    -> single post of "quote" post type only',
        '// page.php            -> static pages',
        '// page-about.php      -> static page with slug "about"',
        '// front-page.php      -> site front page (overrides index.php)',
        '',
        '// Example single-quote.php',
        '<?php',
        'get_header();                           // load header.php',
        'if (have_posts()) {',
        '    while (have_posts()) {',
        '        the_post();',
        '        ?>',
        '        <article>',
        '            <blockquote><?php the_content(); ?></blockquote>',
        '            <cite>&mdash; <?php the_title(); ?></cite>',
        '        </article>',
        '        <?php',
        '    }',
        '}',
        'get_footer();                           // load footer.php',
        '```',
        '',
        '### ## Wiring It Together',
        'A complete plugin that creates a "Testimonial" custom post type with a shortcode and proper asset enqueuing:',
        '```php',
        '<?php',
        '/**',
        ' * Plugin Name: Testimonials Manager',
        ' * Description: Custom testimonials post type with shortcode display',
        ' * Version: 1.0.0',
        ' */',
        '',
        'if (!defined(\'ABSPATH\')) exit;         // block direct file access',
        '',
        '// 1. Register custom post type on WordPress init',
        'add_action(\'init\', \'tm_register_post_type\');',
        '',
        'function tm_register_post_type(): void {',
        '    register_post_type(\'testimonial\', [  // register testimonial CPT',
        '        \'public\' => true,',
        '        \'label\' => \'Testimonials\',',
        '        \'supports\' => [\'title\', \'editor\', \'thumbnail\'],',
        '        \'menu_icon\' => \'dashicons-format-quote\',',
        '    ]);',
        '}',
        '',
        '// 2. Add a shortcode to display testimonials',
        'add_shortcode(\'testimonials\', \'tm_render_testimonials\');',
        '',
        'function tm_render_testimonials(): string {',
        '    $query = new WP_Query([',
        '        \'post_type\' => \'testimonial\',',
        '        \'posts_per_page\' => 5,',
        '        \'orderby\' => \'date\',',
        '        \'order\' => \'DESC\',',
        '    ]);',
        '',
        '    if (!$query->have_posts()) {',
        '        return \'<p>No testimonials yet.</p>\';',
        '    }',
        '',
        '    $output = \'<div class="testimonials-list">\';',
        '    while ($query->have_posts()) {',
        '        $query->the_post();',
        '        $output .= \'<blockquote>\';',
        '        $output .= get_the_content();',
        '        $output .= \'<cite>&mdash; \' . get_the_title() . \'</cite>\';',
        '        $output .= \'</blockquote>\';',
        '    }',
        '    $output .= \'</div>\';',
        '    wp_reset_postdata();                 // restore global post data',
        '    return $output;',
        '}',
        '',
        '// 3. Enqueue stylesheet',
        'add_action(\'wp_enqueue_scripts\', \'tm_enqueue_assets\');',
        '',
        'function tm_enqueue_assets(): void {',
        '    wp_enqueue_style(',
        '        \'tm-styles\',',
        '        plugin_dir_url(__FILE__) . \'testimonials.css\',',
        '        [],',
        '        \'1.0.0\'',
        '    );',
        '}',
        '```',
        'This plugin demonstrates the full cycle: registering a custom post type via an action hook, creating a shortcode with WP_Query and The Loop, and enqueuing frontend assets safely.',
    ]),
    'keyPoints' => [
        'Plugins extend functionality; themes control presentation; never edit core files',
        'Actions run code at specific points; filters modify data before output',
        'Shortcodes are macros that expand to dynamic content in post editor',
        'The Loop iterates through posts using have_posts() and the_post()',
        'WP_Query creates custom database queries outside the main Loop',
        'Always enqueue scripts and styles with wp_enqueue_script/wp_enqueue_style',
    ],
    'tags' => ['PHP', 'WordPress', 'Plugins', 'Themes'],
    'readTimeMin' => 13,
];

// ============================================================
// TOPIC 10: ns-php-deploy
// ============================================================
$topics[] = [
    'id' => 'ns-php-deploy',
    'content' => implode("\n", [
        '### ## What\'s This?',
        'Deployment and tooling in PHP covers the process of taking your application from a development environment to a production server where real users can access it. This includes environment configuration, CI/CD pipelines, server provisioning, caching, queue management, and monitoring. Deployment exists because running code on your local machine is fundamentally different from running it on a production server -- differences in PHP versions, extensions, database credentials, and performance requirements must be handled systematically to prevent downtime and security issues.',
        '',
        '### ## The Big Picture',
        'PHP deployment has evolved from FTP-uploading files to sophisticated CI/CD pipelines using GitHub Actions, GitLab CI, or Laravel Forge. Modern tooling includes Docker for consistent environments, Envoyer for zero-downtime deployments, and services like Laravel Vapor for serverless PHP. Performance optimization involves OPcache, config caching, queue workers, and CDN integration. A proper deployment workflow includes automated testing, environment separation (development/staging/production), secret management, and monitoring with tools like Flare or Sentry.',
        '',
        '### ## Core Ideas',
        '',
        '### Environment Configuration',
        'Environment variables separate configuration from code. Laravel uses a <code>.env</code> file for local development and sets real environment variables on the server. Never commit secrets to version control.',
        '```php',
        '// .env file (never committed to Git)',
        'APP_ENV=production                 // current environment name',
        'APP_DEBUG=false                    // disable debug mode in production',
        'DB_HOST=127.0.0.1                  // database host address',
        'DB_DATABASE=blog                   // database name',
        'DB_USERNAME=deploy_user            // database user',
        'DB_PASSWORD=secret                 // database password (keep secret)',
        '',
        '// Access in code',
        '$dbHost = env(\'DB_HOST\', \'localhost\'); // get env var with fallback default',
        '$isProduction = env(\'APP_ENV\') === \'production\'; // boolean check for environment',
        '```',
        '',
        '### Deployment Pipeline (CI/CD)',
        'A CI/CD pipeline automatically runs tests, builds assets, and deploys your application. GitHub Actions is a common choice for PHP projects.',
        '```yaml',
        '# .github/workflows/deploy.yml',
        'name: Deploy',
        'on:',
        '  push:',
        '    branches: [main]               // trigger on pushes to main branch',
        'jobs:',
        '  deploy:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4   // checkout repository code',
        '      - uses: shivammathur/setup-php@v2 // install PHP with extensions',
        '        with:',
        '          php-version: \'8.2\'',
        '      - run: composer install --no-dev --optimize-autoloader // install prod deps',
        '      - run: php artisan config:cache   // cache config for performance',
        '      - run: php artisan route:cache    // cache routes for performance',
        '      - run: php artisan migrate --force // run database migrations (forced)',
        '```',
        '',
        '### Laravel Optimization Commands',
        'Laravel provides Artisan commands to cache configurations, routes, and views. These dramatically improve performance by reducing file parsing on each request.',
        '```bash',
        '# Run these on each deployment before putting the site live',
        'php artisan config:cache            # merge all config files into one cached file',
        'php artisan route:cache             # serialize route registrations for fast loading',
        'php artisan view:cache              # pre-compile all Blade templates to plain PHP',
        'php artisan event:cache             # cache event/listener registrations',
        'php artisan optimize                # run all of the above at once',
        'php artisan queue:restart           # restart queue workers to pick up code changes',
        '```',
        '',
        '### OPcache',
        'OPcache stores compiled PHP scripts in shared memory, eliminating the need to parse and compile on every request. Enable and configure it in <code>php.ini</code>.',
        '```ini',
        '; php.ini OPcache configuration for production',
        'opcache.enable=1                    ; enable OPcache globally',
        'opcache.memory_consumption=128      ; allocate 128MB for cached compiled scripts',
        'opcache.max_accelerated_files=10000 ; maximum number of cached PHP files',
        'opcache.validate_timestamps=0       ; disable timestamp checks in production (faster)',
        '```',
        '',
        '### Queues and Workers',
        'PHP queues handle time-consuming tasks (email, image processing) asynchronously. Laravel\'s queue system supports Redis, database, and SQS drivers. Workers process jobs in the background.',
        '```php',
        '// Dispatching a job to the queue',
        'use App\\Jobs\\SendWelcomeEmail;',
        '',
        'SendWelcomeEmail::dispatch($user);   // push job onto the default queue',
        'SendWelcomeEmail::dispatch($user)->onQueue(\'emails\'); // push to specific queue',
        '',
        '// Start queue worker (supervisor keeps it running)',
        '// php artisan queue:work --queue=emails,default --sleep=3 --tries=3',
        '',
        '// Supervisor configuration (/etc/supervisor/conf.d/laravel-worker.conf)',
        '[program:laravel-worker]',
        'process_name=%(program_name)s_%(process_num)02d',
        'command=php /var/www/artisan queue:work --sleep=3 --tries=3 --max-time=3600',
        'autostart=true                      ; start worker when supervisor starts',
        'autorestart=true                    ; restart worker if it crashes',
        'numprocs=4                          ; run 4 worker processes in parallel',
        '```',
        '',
        '### Server Provisioning (Laravel Forge)',
        'Laravel Forge automates server provisioning on DigitalOcean, AWS, Linode, and others. It installs Nginx, PHP, MySQL, Redis, and configures queue workers, cron jobs, and SSL certificates.',
        '```bash',
        '# Forge handles these tasks automatically:',
        '# - Creates a server with Nginx, PHP 8.x, MySQL/PostgreSQL, Redis',
        '# - Configures Nginx sites with SSL via Let\'s Encrypt',
        '# - Sets up queue workers with Supervisor',
        '# - Configures cron jobs for scheduled tasks (php artisan schedule:run)',
        '# - Manages deployment scripts (git pull, composer install, migrations)',
        '# - Monitors server health and sends alerts',
        '#',
        '# Example deployment script configured in Forge:',
        '# cd /home/forge/example.com',
        '# git pull origin main',
        '# composer install --no-dev --no-interaction --optimize-autoloader',
        '# if [ -f artisan ]; then',
        '#   php artisan migrate --force',
        '#   php artisan config:cache',
        '#   php artisan route:cache',
        '#   php artisan view:cache',
        '#   php artisan queue:restart',
        '# fi',
        '```',
        '',
        '### ## Wiring It Together',
        'A complete GitHub Actions deployment workflow for a Laravel application:',
        '```yaml',
        '# .github/workflows/deploy.yml',
        'name: Deploy Laravel Application',
        'on:',
        '  push:',
        '    branches: [main]',
        '',
        'jobs:',
        '  test-and-deploy:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - name: Checkout code',
        '        uses: actions/checkout@v4',
        '',
        '      - name: Setup PHP',
        '        uses: shivammathur/setup-php@v2',
        '        with:',
        '          php-version: \'8.2\'',
        '          extensions: mbstring, pdo_mysql, redis, imagick',
        '',
        '      - name: Install dependencies',
        '        run: composer install --no-progress --prefer-dist --optimize-autoloader',
        '',
        '      - name: Run tests',
        '        run: php artisan test          // run PHPUnit test suite',
        '        env:',
        '          DB_CONNECTION: sqlite        // use SQLite for CI testing',
        '          DB_DATABASE: :memory:',
        '',
        '      - name: Deploy to production',
        '        if: success()                  // only deploy if tests pass',
        '        run: |',
        '          # Using Forge CLI or SSH deploy',
        '          # forge deploy your-site-id',
        '          # Or manually via SSH:',
        '          ssh deploy@example.com "',
        '            cd /var/www/app &&',
        '            git pull origin main &&',
        '            composer install --no-dev --optimize-autoloader &&',
        '            php artisan migrate --force &&',
        '            php artisan config:cache &&',
        '            php artisan route:cache &&',
        '            php artisan view:cache &&',
        '            php artisan queue:restart',
        '          "',
        '```',
        '```php',
        '// config/deploy.php -- deploy configuration checklist',
        'return [',
        '    \'environments\' => [',
        '        \'local\' => [',
        '            \'debug\' => true,',
        '            \'opcache\' => false,',
        '        ],',
        '        \'staging\' => [',
        '            \'debug\' => true,',
        '            \'opcache\' => true,',
        '        ],',
        '        \'production\' => [',
        '            \'debug\' => false,          // never show errors in production',
        '            \'opcache\' => true,          // always enable OPcache',
        '            \'config_cache\' => true,     // cache config on deploy',
        '            \'queue_driver\' => \'redis\', // use Redis for production queues',
        '        ],',
        '    ],',
        '];',
        '```',
        'This ties together environment configuration (env vars), CI/CD pipeline (GitHub Actions), Laravel optimization (config/route/view cache), database migrations, and queue management into a production-ready deployment workflow.',
    ]),
    'keyPoints' => [
        '.env files store environment-specific configuration; never commit secrets to Git',
        'CI/CD pipelines automatically test and deploy code on push to main branch',
        'Laravel optimization: cache config, routes, views, and events for faster response times',
        'OPcache stores compiled PHP in memory; disable timestamp validation in production',
        'Queue workers process background jobs asynchronously; Supervisor keeps them running',
        'Laravel Forge automates server provisioning, Nginx setup, SSL, and deployment scripting',
    ],
    'tags' => ['PHP', 'Deployment', 'DevOps', 'Laravel'],
    'readTimeMin' => 14,
];

// Output JSON
$output = json_encode(['topics' => $topics], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if (json_last_error() !== JSON_ERROR_NONE) {
    fwrite(STDERR, 'JSON encode error: ' . json_last_error_msg() . "\n");
    exit(1);
}
echo $output;
