import fs from "fs";

const srcPath = "src/data/curriculum.ts";
let src = fs.readFileSync(srcPath, "utf8");

function setContent(id, newContent) {
  const idRegex = new RegExp('id: "' + id + '"');
  const idMatch = idRegex.exec(src);
  if (!idMatch) { console.error("Not found:", id); return false; }
  const topicStart = idMatch.index;
  const fromContent = src.indexOf("content:", topicStart);
  if (fromContent === -1) { console.error("No content for:", id); return false; }
  let qPos = fromContent + 8;
  while (qPos < src.length && src[qPos] === " ") qPos++;
  const restAfterContent = src.slice(qPos + 1);
  const fieldPatterns = [',\n            codeExample:', ',\n            tags:', ',\n            keyPoints:'];
  let earliestPos = -1;
  let earliestField = '';
  for (const fp of fieldPatterns) {
    const pos = restAfterContent.indexOf(fp);
    if (pos !== -1 && (earliestPos === -1 || pos < earliestPos)) { earliestPos = pos; earliestField = fp; }
  }
  if (earliestPos === -1) { console.error("Cannot find next field for:", id); return false; }
  const contentFieldEnd = qPos + 1 + earliestPos;
  const before = src.slice(0, fromContent);
  const after = src.slice(contentFieldEnd);
  const escaped = newContent.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${");
  src = before + "content: `" + escaped + "`" + after;
  console.log("Fixed:", id);
  return true;
}

const NL = "\n";
function md(lines) { return lines.join(NL); }

// ============================================================================
// fe-crp — The Critical Rendering Path
// ============================================================================
setContent("fe-crp", md([
  "## Why This Matters",
  "",
  "When a user visits your site, their browser has one job: turn a stream of bytes into a visible, interactive page as fast as possible. Every millisecond of delay in that process directly impacts user experience, conversion rates, and SEO rankings. Google's Core Web Vitals — specifically Largest Contentful Paint (LCP) — are measured in how quickly the critical rendering path completes. As a CTO, understanding this pipeline means you can make informed decisions about framework choice, code splitting, resource loading strategies, and ultimately your users' experience.",
  "",
  "The critical rendering path is the sequence of steps the browser goes through to render any web page. It can be broken into six distinct phases, each with its own performance characteristics and optimization strategies.",
  "",
  "## Step 1: DOM Construction",
  "",
  "The journey begins when the browser's networking layer receives the first byte of HTML. The **HTML parser** — typically running on a dedicated parser thread in modern engines — starts converting bytes into tokens, and tokens into nodes. This is not a batch process; it is a streaming, incremental pipeline.",
  "",
  "### How the Parser Works",
  "",
  "The parser uses a state machine with over 80 distinct states (defined in the HTML specification). When it encounters `<html><body><div class=\"container\">`, it transitions through states for each token: tag open, tag name, attribute name, attribute value, etc. Each complete token is fed to the tree construction algorithm, which appends the appropriate DOM node to the tree.",
  "",
  "Critically, the parser is **not** the only consumer of the byte stream. Modern browsers implement a **preload scanner** — a lightweight secondary parser that skips ahead of the main parser to discover subresources (images, stylesheets, scripts) before the main parser reaches them. The preload scanner initiates fetches for these resources in parallel, dramatically reducing overall load time. This is why putting `<link rel=\"preload\">` hints in `<head>` allows the preload scanner to act even earlier.",
  "",
  "### The Script Blocking Problem",
  "",
  "When the parser encounters a `<script>` tag (without `async` or `defer`), everything stops. The parser pauses, the script is fetched (if external), executed, and only then does parsing resume. This happens because scripts may use `document.write()` to inject HTML that changes the document's structure.",
  "",
  "```html",
  "<!-- BAD: this blocks DOM construction entirely -->",
  "<head>",
  "  <script src=\"analytics.js\"></script>  <!-- fetch + execute before proceeding -->",
  "  <link rel=\"stylesheet\" href=\"styles.css\">",
  "</head>",
  "",
  "<!-- GOOD: scripts load without blocking -->",
  "<head>",
  "  <link rel=\"stylesheet\" href=\"styles.css\">",
  "  <script defer src=\"analytics.js\"></script>  <!-- fetched in parallel, executed after parse -->",
  "</head>",
  "```",
  "",
  "The performance impact is dramatic: if a render-blocking script is in `<head>`, the browser may stall for hundreds of milliseconds before the user sees anything. This is why **script placement and loading strategy are the single most impactful frontend performance decisions you can make**.",
  "",
  "| Script Strategy | Blocks Parser? | Execution Order | Use Case |",
  "|---|---|---|---|",
  "| Normal (no attr) | Yes | Immediate | Legacy code that must run synchronously |",
  "| `defer` | No | After parse, before DOMContentLoaded | Most scripts — guaranteed order |",
  "| `async` | No | When fetched (any time) | Independent scripts (analytics, ads) |",
  "| `type=\"module\"` | No | Deferred by default | Modern code with imports |",
  "",
  "## Step 2: CSSOM Construction",
  "",
  "Parallel to DOM construction, the browser processes CSS to build the **CSS Object Model (CSSOM)**. CSS bytes arrive, are tokenized, and the specification's cascade rules are applied to produce a tree of computed styles.",
  "",
  "### Why CSSOM Is Render-Blocking",
  "",
  "The browser **cannot render a single pixel** until the CSSOM is built. Why? Because the Render Tree (step 3) requires computed styles for every visible element. Without knowing a `div`'s width or background color, the browser cannot lay it out or paint it. This is fundamentally different from script blocking: scripts block DOM construction, but CSS blocks the **entire rendering pipeline**.",
  "",
  "The practical implication: only the CSS needed for the **initial viewport** should block rendering. CSS files that are only needed for secondary content (below the fold, modals, secondary pages) should be deferred:",
  "",
  "```html",
  "<!-- Critical CSS: blocks rendering -->",
  "<link rel=\"stylesheet\" href=\"critical.css\">",
  "",
  "<!-- Non-critical CSS: does NOT block rendering -->",
  "<link rel=\"stylesheet\" href=\"non-critical.css\" media=\"print\" onload=\"this.media='all'\">",
  "```",
  "",
  "The `media` attribute trick tells the browser that this stylesheet is for `print` initially — the browser considers it non-blocking and does not wait for it. When it loads, the `onload` handler switches it to `all`, applying the styles. This pattern can shave hundreds of milliseconds off LCP.",
  "",
  "### Specificity and the Cascade",
  "",
  "The CSSOM is not just a 1:1 copy of CSS rules. Every rule goes through the cascade: origin (user agent < user < author < `!important`), specificity (inline > ID > class > tag), and source order. The browser computes the final style for each element by resolving all matching rules through this cascade. Understanding specificity is not trivia — it directly affects debugging time and stylesheet maintainability. A rule of thumb: **keep specificity flat** (use only class selectors) to avoid the cascade war that plagues large codebases.",
  "",
  "## Step 3: Render Tree Construction",
  "",
  "With DOM and CSSOM ready, the browser walks both trees simultaneously to build the **Render Tree**. Each Render Tree node pairs a DOM node with its computed style. Nodes with `display: none` are excluded (they produce no box). `visibility: hidden` nodes are included but rendered invisibly. `head` and its children are excluded. Pseudo-elements like `::before` are included as Render Tree nodes even though they don't exist in the DOM.",
  "",
  "The Render Tree is the **input to layout**. Every optimization that reduces the number of Render Tree nodes or their nesting depth reduces layout complexity.",
  "",
  "## Step 4: Layout (Reflow)",
  "",
  "Layout is the process of calculating **geometry**: the exact position and size of every Render Tree node. The root `<html>` element occupies the viewport. From there, layout flows recursively: block elements stack vertically (in normal flow), inline elements flow horizontally, floats are positioned according to complex rules, flexbox and grid distribute space according to their algorithms.",
  "",
  "### The Cost of Layout",
  "",
  "Layout is the most expensive rendering operation because it requires the browser to calculate every dimension, compute how they affect sibling and parent dimensions, and potentially re-run calculations when changes propagate. In a document with thousands of DOM nodes, a full layout can take tens of milliseconds — easily exceeding a single frame budget (16.6ms).",
  "",
  "**Layout thrashing** is the practice of interleaving DOM reads and writes in a way that forces the browser to recalculate layout repeatedly:",
  "",
  "```javascript",
  "// BAD: Each iteration forces a synchronous reflow",
  "for (let i = 0; i < items.length; i++) {",
  "  const w = items[i].offsetWidth;  // forces layout (reads latest value)",
  "  items[i].style.width = (w + 10) + 'px';  // invalidates layout for next read",
  "}",
  "",
  "// GOOD: Batch all reads, then batch all writes",
  "const widths = Array.from(items).map(el => el.offsetWidth);",
  "items.forEach((el, i) => { el.style.width = (widths[i] + 10) + 'px'; });",
  "```",
  "",
  "Layout thrashing is one of the most common causes of jank in real-world applications. It's especially dangerous in scroll handlers, resize handlers, and requestAnimationFrame loops where it runs every frame. Tools like Chrome DevTools' Performance tab can identify forced reflows by recording layout events triggered outside the natural layout pass.",
  "",
  "### Layout Properties vs Paint/Composite Properties",
  "",
  "Not all CSS changes trigger layout. Properties fall into three categories:",
  "",
  "| Category | Examples | Triggers | Cost |",
  "|---|---|---|---|",
  "| Layout | width, height, padding, margin, top, left, font-size | Layout + Paint + Composite | **Highest** |",
  "| Paint | color, background-color, box-shadow, border-radius | Paint + Composite (no layout) | Medium |",
  "| Composite | transform, opacity | Composite only | **Lowest** |",
  "",
  "Using `transform` for animations (instead of `top`/`left`) and `opacity` for fade effects (instead of `visibility` + `display`) are the single most impactful CSS performance optimizations available.",
  "",
  "## Step 5: Paint",
  "",
  "Paint converts each Render Tree node into actual pixel draw commands. The browser's painting engine (Skia in Chrome, Core Graphics in Safari) generates a sequence of operations: fill rectangle, draw text, stroke border, decode and blit image. These operations are recorded in a **display list** — an optimized command buffer that can be replayed without re-executing layout or paint on subsequent frames (if only composite properties change).",
  "",
  "Painting is expensive for elements with complex visual effects: shadows, gradients, border-radius with overflow clipping, and filters. These effects significantly increase the number of draw commands and may trigger rasterization on the CPU instead of the GPU.",
  "",
  "## Step 6: Compositing",
  "",
  "Compositing is the final step: the browser takes all painted layers and blends them together on the GPU. Layers are created automatically when the browser detects that an element would benefit from independent compositing — elements with `position: fixed`, `transform` animations, `opacity` transitions, `<video>` elements, `<canvas>`, or elements with `will-change: transform`.",
  "",
  "Each layer is painted into a separate GPU texture. When only `transform` or `opacity` changes, the browser simply repositions or re-blends existing textures on the GPU — no layout, no repaint. This is why 60fps animations are achievable with `transform` but nearly impossible with `width` or `top`.",
  "",
  "**But layers are not free.** Each layer consumes GPU memory. Creating too many layers (or promoting everything with `will-change: transform`) can cause GPU memory pressure and degrade performance, especially on mobile devices. Use layers strategically for elements that actually animate.",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Audit your critical path.** Measure how many round trips your HTML requires before render. Each external resource (CSS, font, render-blocking script) adds at least one network round trip.",
  "2. **Inline critical CSS.** The CSS needed for above-the-fold content should be inlined in `<head>` to eliminate a network round trip for the initial render.",
  "3. **Defer everything non-critical.** Scripts with `defer` or `async`, CSS with `media=\"print\"` trick, fonts with `font-display: swap`.",
  "4. **Prefer `transform` and `opacity` for animations.** They are the only properties that guarantee compositor-only updates.",
  "5. **Batch DOM reads and writes.** Use libraries like FastDOM or a simple read-batch-write pattern to prevent layout thrashing.",
  "6. **Layer count matters.** Profile with `chrome://tracing` or DevTools to ensure you're not creating excessive compositor layers.",
  "7. **Use a performance budget.** Track CRP length (time to first paint, LCP) in CI and alert on regressions.",
]));

// ============================================================================
// fe-v8 — V8 Engine: JIT Compilation & Garbage Collection
// ============================================================================
setContent("fe-v8", md([
  "## Why This Matters",
  "",
  "V8 is not just a JavaScript engine — it's the runtime that powers Chrome, Node.js, Deno, and Edge. When your Node.js server struggles with memory or your React app feels sluggish, the root cause is often how V8 manages your code. Understanding V8's JIT compilation, hidden classes, and garbage collection is what separates engineers who can debug performance issues from those who blindly add more hardware.",
  "",
  "## The Tiered Compilation Pipeline",
  "",
  "V8 does not execute JavaScript by interpreting the source directly. It uses a sophisticated **two-tier compilation pipeline** that balances fast startup (interpretation) with peak throughput (optimized machine code).",
  "",
  "### Tier 1: Ignition — The Baseline Interpreter",
  "",
  "When V8 first sees a JavaScript file, the **parser** converts it to an Abstract Syntax Tree (AST). V8 has two parsers: the **preparser** skips functions that are only declared but not immediately executed (saving time and memory), and the **full parser** builds the complete AST for code that actually runs.",
  "",
  "The AST is fed into **Ignition**, V8's register-machine interpreter, which produces **bytecode** — a compact, platform-independent intermediate representation. Ignition executes this bytecode directly. Bytecode execution is fast enough for most code (roughly 2-5x slower than native), but the real benefit is that it allows V8 to collect type information before committing to optimized compilation.",
  "",
  "```javascript",
  "// The preparser skips this entire function body on initial parse",
  "function initExpensiveModule() {",
  "  const data = loadHugeConfig();",
  "  const worker = new Worker('processor.js');",
  "  worker.postMessage(data);",
  "}",
  "",
  "// If initExpensiveModule() is never called, V8 never fully parses it",
  "// This is why wrapping module initialization in a function saves startup time",
  "```",
  "",
  "### Tier 2: TurboFan — The Optimizing JIT Compiler",
  "",
  "Every time a function executes, V8 records information about the types of values flowing through it — numbers, strings, objects with specific shapes — in a **Feedback Vector** attached to the function. When a function becomes \"hot\" (executed many times), TurboFan reads this feedback and speculatively generates highly optimized machine code based on the observed types.",
  "",
  "TurboFan makes assumptions like \"this property access always reads from objects with shape X\" and compiles direct memory offset loads instead of property lookups. If the assumptions hold, execution is orders of magnitude faster than bytecode. If they don't — if a different type appears — TurboFan **deoptimizes**: execution falls back to Ignition bytecode, and TurboFan may recompile with broader type feedback.",
  "",
  "**The key insight for developers**: consistent types in hot functions are critical. If a function parameter is sometimes a number and sometimes a string, TurboFan cannot optimize effectively and the function remains in slow bytecode. This is why TypeScript (or at least type discipline) matters for performance, not just correctness.",
  "",
  "## Hidden Classes (Shapes) and Inline Caches",
  "",
  "V8 represents object layout using **hidden classes** (also called Maps or Shapes). When you write:",
  "",
  "```javascript",
  "const obj = { name: 'Alice', age: 30 };",
  "const obj2 = { name: 'Bob', age: 25 };",
  "// obj and obj2 share the same hidden class",
  "```",
  "",
  "V8 assigns a hidden class to `obj` with two properties at specific offsets. When `obj2` is created with properties in the same order, V8 reuses the same hidden class. Property access becomes a fixed-offset load — as fast as accessing a C struct field.",
  "",
  "**The transition problem:** Adding properties after construction, or deleting them, triggers a hidden class transition. If you add properties inconsistently across objects, each unique property order creates a new hidden class, degrading property access to dictionary-mode lookups:",
  "",
  "```javascript",
  "function Point(x, y) {",
  "  this.x = x;",
  "  this.y = y;",
  "}",
  "const p1 = new Point(1, 2);  // hidden class C1: {x: offset_0, y: offset_1}",
  "p1.z = 3;                    // transitions to C2: {x, y, z}",
  "const p2 = new Point(3, 4);  // stays on C1 — okay",
  "p2.label = 'origin';         // transitions to C3: different shape!",
  "// Now p1 and p2 have different hidden classes — slower polymorphic access",
  "```",
  "",
  "**Inline Caches (ICs)** are the mechanism V8 uses to remember property offsets. Each property access site starts in monomorphic state (one hidden class — fastest), degrades to polymorphic (2-4 classes — slower), and then to megamorphic (5+ classes — V8 falls back to dictionary lookup). In hot code paths, ensuring objects have consistent shapes is one of the most impactful optimizations.",
  "",
  "## Generational Garbage Collection",
  "",
  "V8 uses a **generational GC** based on decades of empirical observation: most objects die young. The heap is split into two generations:",
  "",
  "| Generation | Algorithm | Frequency | \u00a0Trigger\u00a0 |",
  "|---|---|---|---|",
  "| **Young (Nursery)** | Scavenger — semi-space copying collector | Frequent (~every few MB allocated) | Minor GC pause: <1ms |",
  "| **Old** | Mark-Sweep-Compact | Infrequent (triggered by old-gen fragmentation) | Major GC pause: ~5-50ms |",
  "",
  "### Young Generation (Scavenger)",
  "",
  "The young generation is a semi-space allocator. Objects are allocated in the \"from-space.\" When it fills up, the Scavenger traces live objects and copies them to \"to-space.\" Dead objects are left behind, and the space is reclaimed in one operation. Objects that survive two Scavenger cycles are **promoted** to the old generation.",
  "",
  "Scavenger pauses are typically under 1ms, making them imperceptible. However, if many objects are promoted prematurely — because they are referenced by long-lived objects — they bloat the old generation and increase major GC cost.",
  "",
  "### Old Generation (Mark-Sweep-Compact)",
  "",
  "The old generation uses a concurrent mark-sweep-compact collector. **Marking** identifies live objects by tracing from GC roots (global objects, stack variables, active closures). Marking runs **concurrently** on background threads to avoid blocking JavaScript execution. After marking, **sweeping** reclaims dead objects, and **compacting** defragments memory by sliding live objects together.",
  "",
  "Major GC pauses, even with concurrent marking, can still cause visible jank in the browser or latency spikes in Node.js. The key to minimizing their impact is controlling old-generation growth: avoid creating long-lived reference chains that keep young objects alive, and be mindful of object allocation rates in hot paths.",
  "",
  "## Practical Implications for Developers",
  "",
  "1. **Initialize all properties in the constructor/object literal.** Never add properties after construction in hot code paths — this forces hidden class transitions.",
  "2. **Keep types consistent.** Don't change the type of a function parameter or property value. Monomorphic is always faster than polymorphic.",
  "3. **Prefer small, short-lived objects.** They are collected by the fast Scavenger without ever reaching the old generation.",
  "4. **Avoid large object graphs retained by closures.** Event listeners holding references to large data structures prevent GC entirely.",
  "5. **Use `--trace-gc` in Node.js** to understand GC behavior. Unexpected old-gen growth points to object retention issues.",
  "6. **For CTOs:** Consider the runtime characteristics of your workload. If your Node.js service has frequent latency spikes, profile GC patterns before blaming the infrastructure.",
]));

// ============================================================================
// fe-event-loop — The Event Loop, Tasks & Microtasks
// ============================================================================
setContent("fe-event-loop", md([
  "## Why This Matters",
  "",
  "JavaScript runs on a single thread. Despite this fundamental constraint, it handles thousands of concurrent network requests, animates 60fps UIs, and processes user input without blocking. This magic is the event loop. Misunderstanding its queue priorities is the root cause of subtle bugs — UI that doesn't update, animations that stutter, or promises that seem to execute in the wrong order. Every JavaScript developer, from bootcamp graduate to CTO, needs an accurate mental model of the event loop to write predictable code.",
  "",
  "## The Single-Threaded Foundation",
  "",
  "JavaScript's runtime uses a single call stack. When a function calls another function, a new execution context is pushed onto the stack. When a function returns, its context is popped. The runtime executes exactly one thing at a time, and nothing else can happen while the stack is non-empty.",
  "",
  "```javascript",
  "function a() { b(); }",
  "function b() { c(); }",
  "function c() { console.log('hello'); }",
  "a();",
  "// Stack: [global] -> [a] -> [b] -> [c] -> [b] -> [a] -> [global]",
  "// Execution is strictly sequential through this chain",
  "```",
  "",
  "This single-threaded model has a profound consequence: **long-running synchronous operations freeze the entire application**. A 500ms synchronous loop in the browser freezes all UI updates, user input, and network event processing. In Node.js, it blocks all incoming request processing. The only way to avoid this is to never block the stack for more than a few milliseconds at a time.",
  "",
  "## The Event Loop: What It Actually Is",
  "",
  "The event loop is not part of the JavaScript language — it is provided by the **runtime environment** (the browser or Node.js). It is a continuous loop that checks whether there are pending tasks to execute, and if so, runs them one at a time on the call stack. The loop itself has a well-defined order of operations specified by the HTML standard:",
  "",
  "```",
  "While (true):",
  "  1. Pick the oldest macrotask from the macrotask queue",
  "  2. Execute it (run its callbacks on the stack until empty)",
  "  3. Drain the ENTIRE microtask queue (execute all microtasks until empty)",
  "  4. Check if rendering is needed (update style, layout, paint)",
  "  (Repeat)",
  "```",
  "",
  "## Macrotasks vs Microtasks",
  "",
  "Understanding the two types of tasks — and their prioritization — is the most important part of the event loop model.",
  "",
  "### Macrotasks (Tasks)",
  "",
  "Macrotasks are the basic unit of work in the event loop. Each iteration of the loop processes exactly one macrotask. Sources of macrotasks include:",
  "",
  "- Parsing a chunk of HTML",
  "- Firing a DOM event (click, keydown, mousemove)",
  "- `setTimeout()` and `setInterval()` callbacks",
  "- I/O completion callbacks (fetch, file reads, sockets)",
  "- `requestAnimationFrame()` callbacks (actually processed in the render step, but often grouped conceptually)",
  "",
  "### Microtasks",
  "",
  "Microtasks are higher-priority work that must be completed before the event loop can proceed to the next macrotask. The microtask queue is drained **completely** — if a microtask enqueues another microtask, the new one is processed immediately, before the next macrotask or render step. Sources of microtasks include:",
  "",
  "- `Promise.then()`, `Promise.catch()`, `Promise.finally()`",
  "- `queueMicrotask()`",
  "- `MutationObserver` callbacks",
  "",
  "```javascript",
  "console.log('1 - synchronous');",
  "",
  "setTimeout(() => {",
  "  console.log('5 - macrotask');",
  "}, 0);",
  "",
  "Promise.resolve()",
  "  .then(() => console.log('3 - microtask 1'))",
  "  .then(() => console.log('4 - microtask 2'));",
  "",
  "console.log('2 - synchronous');",
  "",
  "// Output: 1, 2, 3, 4, 5",
  "// Microtasks (3, 4) run before the macrotask (5),",
  "// even though setTimeout was registered first",
  "```",
  "",
  "### Why This Ordering Matters",
  "",
  "The microtask-first ordering has critical practical implications:",
  "",
  "1. **Microtask starvation:** If a microtask recursively enqueues itself, the microtask queue never empties, and the event loop never reaches macrotasks or rendering. The UI freezes, and `setTimeout` callbacks never fire. This is a real bug in production code:",
  "",
  "```javascript",
  "// DANGEROUS: This will freeze the UI",
  "function loop() {",
  "  queueMicrotask(loop);  // never-ending microtask chain",
  "}",
  "loop();",
  "// No rendering ever happens again",
  "```",
  "",
  "2. **Promise resolution order:** Since `.then()` callbacks are microtasks, a resolved promise's callbacks always run before any queued `setTimeout` callback, even if the promise was resolved before the timeout was created.",
  "",
  "3. **Rendering delay:** The browser only renders between macrotasks. If you batch your DOM changes inside a microtask, they will be applied before the next render — which is efficient. If you batch them in a macrotask, the browser may render before your changes.",
  "",
  "## requestAnimationFrame and the Render Step",
  "",
  "After draining microtasks, the browser checks if a render is needed. Renders happen approximately every 16.6ms (60fps), but the browser may skip frames if the page is not changing or if the event loop is busy.",
  "",
  "The render step includes:",
  "1. Firing `requestAnimationFrame` callbacks (these run **before** style calculation, making them the correct place to schedule DOM changes for the upcoming frame)",
  "2. Computing styles for changed elements",
  "3. Performing layout (if any layout properties changed)",
  "4. Painting layers",
  "5. Compositing layers on the GPU",
  "",
  "`requestAnimationFrame` is **not** a macrotask or microtask — it is queued separately and processed during the render step. This makes it the ideal scheduling primitive for visual updates:",
  "",
  "```javascript",
  "// BAD: setTimeout for animation — not synchronized with frame timing",
  "function animate() {",
  "  element.style.transform = `translateX(${x++}px)`;",
  "  setTimeout(animate, 1000 / 60);  // may fire mid-frame or miss frames",
  "}",
  "",
  "// GOOD: requestAnimationFrame — synchronized with paint cycle",
  "function animate() {",
  "  element.style.transform = `translateX(${x++}px)`;",
  "  requestAnimationFrame(animate);  // fires exactly once before each paint",
  "}",
  "```",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Never block the stack.** Synchronous loops, heavy computations, or synchronous I/O in the main thread destroys responsiveness. Use Web Workers or offload to the backend.",
  "2. **Use microtasks for synchronous-looking async code.** Promises and `queueMicrotask` are the correct tools for sequencing dependent operations without frame delays.",
  "3. **Use macrotasks for yielding to the UI.** `setTimeout(0)` or `setImmediate` (Node.js) allows rendering between operations.",
  "4. **Always use `requestAnimationFrame` for DOM animations.** Not `setTimeout`. Not `setInterval`. This is non-negotiable for smooth 60fps UIs.",
  "5. **Profile with DevTools Performance tab.** The event loop visualization shows exactly where frames are dropped and which tasks cause long frame times.",
]));

// ============================================================================
// fe-browser-security — Browser Security Model
// ============================================================================
setContent("fe-browser-security", md([
  "## Why This Matters",
  "",
  "Nearly every web application vulnerability — data breaches, account takeover, content injection — traces back to a misunderstanding of the browser's security model. As a builder of web applications, you don't need to be a security researcher, but you must understand the fundamental boundaries the browser enforces and how to safely relax them. This knowledge directly impacts how you architect APIs, manage sessions, handle user content, and configure your deployment.",
  "",
  "## The Same-Origin Policy (SOP): The Foundation",
  "",
  "The Same-Origin Policy is the cornerstone of web security. It defines a boundary: code running on origin A cannot read data from origin B. An **origin** is defined by three components that must all match: **protocol** (https), **hostname** (example.com), and **port** (443).",
  "",
  "```",
  "Same origin:  https://example.com/page1  vs  https://example.com/page2",
  "Different:    https://example.com         vs  https://api.example.com     (different host)",
  "Different:    https://example.com         vs  http://example.com          (different protocol)",
  "Different:    https://example.com         vs  https://example.com:8080    (different port)",
  "```",
  "",
  "### What SOP Allows and Blocks",
  "",
  "SOP makes a critical distinction between **reading** and **writing**:",
  "",
  "- SOP **allows writes**: you can submit a `<form>` to any origin, load a `<script>` from any origin, load an `<img>` from any origin. This is why CSRF attacks work — the browser lets you send a POST request to `https://bank.com/transfer` from `https://evil.com`.",
  "- SOP **blocks reads**: the `evil.com` page cannot read the response from `bank.com`. It cannot access the DOM of a `bank.com` iframe. It cannot make a `fetch()` request to `bank.com` and read the response.",
  "",
  "This asymmetry — write is allowed, read is blocked — is the root cause of most web security vulnerabilities. CSRF exploits the write permission. XSS tries to bypass the read restriction by injecting code that runs in the victim origin's context.",
  "",
  "## CORS: Controlled SOP Relaxation",
  "",
  "Modern web applications need legitimate cross-origin reads. Your SPA at `app.example.com` needs to read from `api.example.com`. This is where **Cross-Origin Resource Sharing (CORS)** comes in — a mechanism for servers to selectively opt-in to cross-origin reads.",
  "",
  "CORS works through HTTP headers. When the browser makes a cross-origin `fetch()` request, it checks the response for:",
  "",
  "```http",
  "Access-Control-Allow-Origin: https://app.example.com",
  "Access-Control-Allow-Methods: GET, POST, PUT, DELETE",
  "Access-Control-Allow-Headers: Content-Type, Authorization",
  "Access-Control-Allow-Credentials: true  ;; allows cookies in the request",
  "```",
  "",
  "For requests that may affect server state (non-simple requests — anything with custom headers, `application/json` content type, or non-standard methods), the browser sends a **preflight** `OPTIONS` request before the actual request. The server must respond with appropriate CORS headers or the actual request is blocked.",
  "",
  "```javascript",
  "// Browser behavior for a cross-origin fetch:",
  "fetch('https://api.example.com/data', {",
  "  method: 'POST',",
  "  headers: { 'Content-Type': 'application/json' },  // non-simple!",
  "  credentials: 'include',                           // include cookies",
  "});",
  "// 1. Browser sends OPTIONS preflight to https://api.example.com/data",
  "// 2. If OPTIONS response lacks proper CORS headers, the POST is never sent",
  "// 3. If OPTIONS response is correct, the POST is sent and the response is checked",
  "```",
  "",
  "The most common CORS misconfiguration in production is echoing the `Origin` header back:",
  "",
  "```",
  "Access-Control-Allow-Origin: *  ;; or worse: req.headers.origin",
  "```",
  "",
  "This effectively disables SOP for any origin. Production APIs should use an explicit allowlist of known origins.",
  "",
  "## Content Security Policy (CSP)",
  "",
  "CSP is a defense-in-depth mechanism that tells the browser what resources are allowed to load on your page. It is implemented via an HTTP response header:",
  "",
  "```http",
  "Content-Security-Policy: default-src 'self'; script-src 'self' https://cdn.example.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; report-uri /csp-violations",
  "```",
  "",
  "A well-configured CSP prevents XSS even if an attacker manages to inject a `<script>` tag — the browser refuses to execute it because the script source is not in the policy. The directives you'll use most:",
  "",
  "| Directive | Controls |",
  "|---|---|",
  "| `default-src` | Fallback for all resource types |",
  "| `script-src` | JavaScript sources (most critical for XSS prevention) |",
  "| `style-src` | CSS sources |",
  "| `img-src` | Image sources |",
  "| `connect-src` | URLs fetched via fetch(), XHR, WebSocket |",
  "| `frame-ancestors` | Which origins can embed the page in an iframe (replaces X-Frame-Options) |",
  "| `report-uri` | Where to send violation reports |",
  "",
  "**The `'unsafe-inline'` trap:** To effectively prevent XSS, `script-src` should NOT include `'unsafe-inline'`. Instead, use:",
  "- **Nonces:** `<script nonce=\"random123\">` — the server generates a random nonce per response, and the CSP includes `script-src 'nonce-random123'`.",
  "- **Hashes:** For inline scripts that are part of the application (not user input), use `'sha256-...'`.",
  "",
  "## XSS, CSRF, and Clickjacking",
  "",
  "### Cross-Site Scripting (XSS)",
  "",
  "XSS occurs when an attacker injects script code into a page viewed by other users. Three types:",
  "",
  "1. **Reflected XSS:** The injected payload is part of the request (e.g., a search parameter rendered without escaping). The attacker sends a crafted link to the victim, who clicks it and executes the payload.",
  "2. **Stored XSS:** The payload is persisted on the server (e.g., a forum post containing `<script>`). Every user who views the post executes the payload.",
  "3. **DOM-based XSS:** The vulnerability exists entirely in client-side JavaScript (e.g., `innerHTML = location.hash`). No server interaction needed.",
  "",
  "Prevention is layered: **contextual output encoding** (using a templating engine that auto-escapes), **CSP** (to block injected scripts even if encoding fails), and **sanitization** (for rich content, using DOMPurify or similar).",
  "",
  "### Cross-Site Request Forgery (CSRF)",
  "",
  "CSRF tricks an authenticated user's browser into making a state-changing request to a different site. Since SOP allows writes, `evil.com` can submit a form to `bank.com/transfer`. The browser includes the user's cookies for `bank.com`, making the request appear legitimate.",
  "",
  "Modern browsers prevent CSRF with the `SameSite` cookie attribute:",
  "",
  "```",
  "Set-Cookie: session=abc123; SameSite=Strict; Secure; HttpOnly",
  "```",
  "",
  "- `SameSite=Strict`: cookie is never sent on cross-origin requests.",
  "- `SameSite=Lax`: cookie is sent on top-level navigations (GET only).",
  "- `SameSite=None`: cookie is sent on all cross-origin requests (must also set `Secure`).",
  "",
  "For APIs that still need additional CSRF protection (e.g., if cookies are set to `None`), use custom request headers or anti-CSRF tokens.",
  "",
  "### Clickjacking",
  "",
  "An attacker embeds your site in a transparent `<iframe>` and overlays their own UI elements, tricking users into clicking your buttons (e.g., \"Delete Account\"). Prevention: `X-Frame-Options: DENY` or the CSP directive `frame-ancestors 'self'`.",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Default-deny CORS.** Start with an empty allowlist and add origins only as needed. Never echo the Origin header.",
  "2. **CSP is not optional.** Start with a strict policy (no `'unsafe-inline'`) and use report-only mode to discover violations before enforcing.",
  "3. **All cookies should have SameSite=Strict or Lax.** Only use `None` when you have a specific cross-origin need and understand the CSRF implications.",
  "4. **Set `X-Frame-Options: DENY`** unless you explicitly need framing. Then use CSP `frame-ancestors` for fine-grained control.",
  "5. **Use `HttpOnly` cookies** for session tokens — JavaScript should never access the session ID.",
  "6. **Regular security headers audit.** Use tools like securityheaders.com to check your production deployment's security posture.",
]));

// ============================================================================
// fe-wasm — WebAssembly
// ============================================================================
setContent("fe-wasm", md([
  "## Why This Matters",
  "",
  "JavaScript was never designed for compute-intensive workloads. Image processing, video encoding, 3D physics simulations, large-scale data transformations — these tasks are 10-50x slower in JavaScript than in C++ or Rust. WebAssembly (Wasm) closes this gap by providing a portable, sandboxed, near-native execution environment that runs alongside JavaScript. For CTOs evaluating architectural choices, Wasm represents a shift from \"everything must be JavaScript or an API call\" to \"compile compute-heavy logic once and run it anywhere.\"",
  "",
  "## What WebAssembly Actually Is",
  "",
  "WebAssembly is not a language you write — it is a **compilation target**. You write code in C, C++, Rust, Go, or (experimentally) Python and Java, and compile it to a `.wasm` binary. This binary is a low-level instruction format designed for fast decoding and execution. The browser's Wasm engine validates the binary, compiles it to machine code (often using the same optimizing compiler backend as the JavaScript JIT), and runs it in a sandboxed environment with no access to the host system unless explicitly granted.",
  "",
  "## Architecture of a Wasm Module",
  "",
  "A `.wasm` binary contains:",
  "",
  "1. **Functions** — typed function bodies with local variables, control flow (blocks, loops, if/else), and calls. Types are limited to integers (i32, i64) and floats (f32, f64) — no strings, no objects, no closures.",
  "2. **Linear Memory** — a single contiguous array of bytes, starting at page offset 0. This is where all data lives. The module imports or exports memory, and both Wasm and JavaScript can read/write it via `ArrayBuffer`.",
  "3. **Table** — an array of function references used for indirect calls (function pointers).",
  "4. **Globals** — module-level mutable or immutable scalar values.",
  "",
  "There is **no garbage collector**. Memory must be explicitly allocated and freed, typically by linking a small allocator (like Rust's allocator or dlmalloc) into the Wasm binary. This gives Wasm predictable memory behavior — no GC pauses — but requires careful memory management.",
  "",
  "## The JS-Wasm Bridge",
  "",
  "JavaScript and Wasm communicate through imports and exports. A Wasm module can export functions that JavaScript calls, and can import JavaScript functions that it calls. Data is passed through linear memory:",
  "",
  "```javascript",
  "// main.js — call Wasm from JavaScript",
  "const wasm = await WebAssembly.instantiateStreaming(",
  "  fetch('filter.wasm'),",
  "  {",
  "    imports: {",
  "      log: (msgPtr, len) => console.log(memoryToString(msgPtr, len)),",
  "    },",
  "  }",
  ");",
  "",
  "// Allocate input in shared memory",
  "const input = new Uint8Array(wasm.instance.exports.memory.buffer);",
  "input.set(imageData, offset);",
  "",
  "// Call Wasm function — processes data in-place",
  "wasm.instance.exports.applyFilter(offset, length);",
  "",
  "// Read the result from the same memory buffer",
  "const result = new Uint8Array(wasm.instance.exports.memory.buffer, offset, length);",
  "```",
  "",
  "The cost of crossing the JS-Wasm boundary is minimal in modern engines — typically less than a native function call overhead. But passing large data structures requires serialization or careful memory management, which adds complexity.",
  "",
  "## When to Use Wasm",
  "",
  "| Scenario | Wasm vs JavaScript | Real-world Examples |",
  "|---|---|---|",
  "| Image/video processing | 5-20x faster | Figma's design renderer, squoosh.app image optimizer |",
  "| Physics simulations | 10-50x faster | 3D game engines (Unity, Unreal) compiled to Wasm |",
  "| Cryptography | 2-10x faster | libsodium compiled to Wasm for client-side crypto |",
  "| Data compression | 3-8x faster | Brotli decompressor for custom formats |",
  "| JSON parsing | 1.5-3x faster | simdjson compiled to Wasm for huge payloads |",
  "| DOM manipulation | Wasm cannot access DOM | Must go through JS bridge — adds overhead |",
  "",
  "**When NOT to use Wasm:** If your bottleneck is DOM manipulation, network I/O, or database queries, Wasm offers no benefit. The JS-to-Wasm-to-JS bridge for DOM calls adds latency. Wasm shines only for CPU-bound computations that can run independently of the DOM.",
  "",
  "## WASI: WebAssembly Beyond the Browser",
  "",
  "The **WebAssembly System Interface (WASI)** defines a set of POSIX-like APIs for Wasm modules running outside the browser — filesystem access, networking, clock, random number generation. WASI-powered runtimes like Wasmtime, Wasmer, and Wamr enable Wasm in server-side applications, edge computing platforms, and plugin systems.",
  "",
  "Production uses of server-side Wasm:",
  "- **Cloudflare Workers / Fastly Compute@Edge:** Run Wasm at the CDN edge for near-zero-latency compute.",
  "- **Plugin systems:** Envoy proxy, Istio service mesh, and Caddy web server use Wasm for extensible filters — users write plugins in any language that compiles to Wasm, without worrying about the host's runtime.",
  "- **Serverless functions:** Wasm's fast startup (sub-millisecond cold start vs ~100ms for Node.js containers) makes it ideal for functions that need to scale from zero instantly.",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Wasm is not a JavaScript replacement.** It is a specialized tool for compute-heavy workloads where JS performance is inadequate.",
  "2. **Consider Wasm for greenfield compute services.** A Rust-based Wasm module running in Cloudflare Workers can serve 10x more requests per dollar than a Node.js Lambda.",
  "3. **Memory management is your responsibility.** Wasm has no GC — predictable but requires careful engineering. Larger teams will find Rust's ownership model easier to manage than manual malloc/free.",
  "4. **Edge runtime + Wasm is a strategic combination.** Fast cold starts, strong sandboxing, language-agnostic compilation — this is the future of serverless compute.",
  "5. **Investigate Wasm for plugin architectures.** Instead of embedding a scripting language (Lua, JavaScript), embed a Wasm runtime. Users write plugins in their language of choice, and the sandbox is automatically enforced.",
]));

// ============================================================================
// fe-closures — Closures, Scope & Execution Contexts
// ============================================================================
setContent("fe-closures", md([
  "## Why This Matters",
  "",
  "Closures are the most misunderstood yet most frequently used feature in JavaScript. They are the mechanism behind callbacks, event handlers, React hooks (useState, useEffect depend on closure capture), and module encapsulation. A shallow understanding of closures leads to stale closure bugs (the infamous React \"stale state in useEffect\" problem), memory leaks from accidental retention, and confusion about variable scoping in loops. A deep understanding separates engineers who fight JavaScript from engineers who wield it.",
  "",
  "## Lexical Scoping: The Foundation",
  "",
  "JavaScript uses **lexical (static) scoping**: the scope of a variable is determined by where it is declared in the source code, not where it is called from. This is in contrast to dynamic scoping (used by Bash, some Lisp dialects), where scope depends on the call stack.",
  "",
  "When JavaScript code executes, the engine creates an **Execution Context** for each function call. Each context contains a **Lexical Environment** — a mapping of variable names to their values — plus a reference to the outer environment (the environment of the enclosing scope) and the `this` binding.",
  "",
  "```javascript",
  "const global = 'global';",
  "",
  "function outer() {",
  "  const outerVar = 'outer';",
  "",
  "  function inner() {",
  "    const innerVar = 'inner';",
  "    console.log(innerVar); // 'inner' — found in own environment",
  "    console.log(outerVar); // 'outer' — found in outer's environment",
  "    console.log(global);   // 'global' — found in global environment",
  "  }",
  "",
  "  inner();",
  "}",
  "",
  "outer();",
  "```",
  "",
  "When `inner()` references `outerVar`, the engine first checks `inner`'s own environment. Not finding it there, it follows the outer reference to `outer`'s environment. Not finding it there, it follows to the global environment. This chain — the **scope chain** — is established at function definition time, not call time.",
  "",
  "## What Is a Closure?",
  "",
  "A closure is created when a function \"remembers\" its lexical environment even after that environment would normally be destroyed. Formally: **a closure is the combination of a function and the lexical environment within which it was declared.**",
  "",
  "```javascript",
  "function createCounter() {",
  "  let count = 0;  // this variable is 'captured' by the closure",
  "",
  "  return {",
  "    increment: function() {",
  "      count++;",
  "      return count;",
  "    },",
  "    getValue: function() {",
  "      return count;",
  "    },",
  "  };",
  "}",
  "",
  "const counter = createCounter();",
  "// createCounter() has finished executing. 'count' should be gone.",
  "// But counter.increment and counter.getValue still reference it.",
  "console.log(counter.increment()); // 1",
  "console.log(counter.increment()); // 2",
  "console.log(counter.getValue());  // 2",
  "```",
  "",
  "When `createCounter()` executes, it creates a local variable `count` and returns two inner functions. After `createCounter()` returns, its execution context is popped from the stack. Under normal circumstances, `count` would be garbage collected. But because the returned functions maintain a reference to `createCounter`'s lexical environment (via their `[[Environment]]` internal slot), the environment — and `count` with it — stays alive.",
  "",
  "This is the essence of a closure: inner functions that survive their parent function \"close over\" the parent's variables, keeping them accessible.",
  "",
  "## Common Closure Patterns and Pitfalls",
  "",
  "### 1. The Loop Variable Trap",
  "",
  "One of the most famous closure bugs:",
  "",
  "```javascript",
  "// BAD: All callbacks log 5, not 0,1,2,3,4",
  "for (var i = 0; i < 5; i++) {",
  "  setTimeout(() => console.log(i), 0);",
  "}",
  "// Output: 5, 5, 5, 5, 5",
  "",
  "// WHY: var i is hoisted to function scope — there is only ONE variable i.",
  "// By the time the setTimeout callbacks execute, the loop has finished and i === 5.",
  "",
  "// FIX 1: Use let (creates a new binding per iteration)",
  "for (let i = 0; i < 5; i++) {",
  "  setTimeout(() => console.log(i), 0);",
  "}",
  "// Output: 0, 1, 2, 3, 4",
  "",
  "// FIX 2: Create a new closure per iteration with an IIFE",
  "for (var i = 0; i < 5; i++) {",
  "  (function(j) {",
  "    setTimeout(() => console.log(j), 0);",
  "  })(i);",
  "}",
  "// Output: 0, 1, 2, 3, 4",
  "```",
  "",
  "This bug is caused by closure capture: all five `setTimeout` callbacks close over the **same** `i`. With `var`, there's only one `i` for the entire function. With `let`, JavaScript creates a new binding for each iteration, so each callback captures its own `i`.",
  "",
  "### 2. Stale Closures in React Hooks",
  "",
  "React's `useEffect` and `useCallback` depend on closure capture. If you forget to list a dependency, the callback captures a stale value:",
  "",
  "```javascript",
  "function Timer() {",
  "  const [count, setCount] = useState(0);",
  "",
  '  // BAD: count is captured once when the effect runs, never updates',
  "  useEffect(() => {",
  "    const id = setInterval(() => {",
  "      setCount(count + 1);  // count is always 0 here",
  "    }, 1000);",
  "    return () => clearInterval(id);",
  "  }, []);  // empty deps — count is never re-captured",
  "}",
  "```",
  "",
  "The fix is either to include `count` in the dependency array or to use the functional form `setCount(c => c + 1)` which does not depend on the closure value.",
  "",
  "### 3. Accidental Memory Retention",
  "",
  "Every closure that survives its parent keeps its entire captured scope alive. This is the source of many memory leaks:",
  "",
  "```javascript",
  "function createLeakyHandler() {",
  "  const hugeData = new Array(1000000).fill('leak');",
  "",
  "  return function handler() {",
  "    console.log('button clicked');",
  "    // handler does NOT use hugeData,",
  "    // but hugeData is still retained because it's in the same scope!",
  "  };",
  "}",
  "",
  "// As long as this handler is attached to an element,",
  "// hugeData (1MB) cannot be garbage collected",
  "button.addEventListener('click', createLeakyHandler());",
  "```",
  "",
  "Modern engines optimize by tracking which variables are actually accessed by the closure. If `hugeData` is not referenced by any closure in that scope, the engine may elide it. However, relying on this optimization is fragile — explicit cleanup is safer.",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Closures are the foundation of functional patterns in JS.** map, filter, reduce, partial application, memoization — all rely on closures.",
  "2. **Never use `var` in loops with async callbacks.** Use `let` or create explicit IIFE scopes. Enforce this with ESLint's `no-loop-func`.",
  "3. **React dependency arrays are closure management.** Every value used inside useEffect/useCallback/useMemo must be in the dependency array. ESLint's `exhaustive-deps` rule is essential.",
  "4. **Audit long-lived closures for memory retention.** Event listeners, WebSocket handlers, and interval callbacks that capture large scopes are common memory leak sources in long-running applications.",
]));

// ============================================================================
// fe-prototypes — Prototypal Inheritance
// ============================================================================
setContent("fe-prototypes", md([
  "## Why This Matters",
  "",
  "JavaScript's prototypal inheritance model is fundamentally different from classical inheritance in languages like Java and Python. Engineers who map classical mental models onto JavaScript write confusing, error-prone code. More importantly, understanding prototypes is essential for debugging property access chains, optimizing hot code paths, and choosing between `class`, `Object.create`, and plain object patterns. If you write JavaScript without understanding `[[Prototype]]`, you are programming by coincidence.",
  "",
  "## The Prototype Chain: The Core Mechanism",
  "",
  "Every JavaScript object has an internal slot called `[[Prototype]]` (accessible via `Object.getPrototypeOf(obj)`). This slot points to another object — its **prototype**. When you access a property on an object, the engine performs the following lookup:",
  "",
  "1. Check if the object has an **own property** with that name (a property directly on the object, not inherited).",
  "2. If not found, follow the `[[Prototype]]` reference to the prototype object.",
  "3. Check the prototype's own properties.",
  "4. If not found, follow that prototype's `[[Prototype]]`.",
  "5. Continue until `[[Prototype]]` is `null` — then return `undefined`.",
  "",
  "```javascript",
  "const parent = { inherited: 'hello' };",
  "const child = Object.create(parent);",
  "child.own = 'world';",
  "",
  "console.log(child.own);       // 'world' — own property",
  "console.log(child.inherited); // 'hello' — found on parent via [[Prototype]] chain",
  "console.log(child.toString);  // function — found on Object.prototype via chain",
  "console.log(child.nonexistent); // undefined — end of chain",
  "```",
  "",
  "This chain is the entire inheritance mechanism. There is nothing more to it. Classes, constructors, `new` — these are all conveniences layered on top of this simple lookup chain.",
  "",
  "## `class` Is Syntactic Sugar",
  "",
  "The `class` keyword (ES2015) provides a familiar syntax for setting up prototype chains, but it does not introduce a new inheritance model:",
  "",
  "```javascript",
  "class Animal {",
  "  constructor(name) { this.name = name; }",
  "  speak() { console.log(this.sound); }",
  "}",
  "",
  "class Dog extends Animal {",
  "  constructor(name) { super(name); this.sound = 'woof'; }",
  "}",
  "",
  "// Under the hood:",
  "// Animal.prototype.speak = function speak() { ... }",
  "// Dog.prototype = Object.create(Animal.prototype)",
  "// Dog.prototype.constructor = Dog",
  "// Dog.prototype.[[Prototype]] === Animal.prototype",
  "```",
  "",
  "When you write `new Dog('Rex')`:",
  "1. A new plain object is created (`{}`)",
  "2. Its `[[Prototype]]` is set to `Dog.prototype`",
  "3. The constructor function (`Dog`) runs with `this` bound to the new object",
  "4. Property `name` is set on the new object as an own property",
  "5. `speak` is accessed via prototype chain: object → Dog.prototype → Animal.prototype",
  "",
  "## `Object.create` — The Primitives Beneath the Class",
  "",
  "`Object.create(proto)` is the fundamental operation: create a new object whose `[[Prototype]]` is the provided argument. Everything else is built on this:",
  "",
  "```javascript",
  "// Pure prototypal pattern (no classes)",
  "const animalMethods = {",
  "  speak() { console.log(this.sound); },",
  "  init(sound) { this.sound = sound; return this; },",
  "};",
  "",
  "const dog = Object.create(animalMethods).init('woof');",
  "dog.speak(); // 'woof'",
  "",
  "const cat = Object.create(animalMethods).init('meow');",
  "cat.speak(); // 'meow'",
  "```",
  "",
  "This pattern — sometimes called the **OLOO pattern** (Objects Linking to Other Objects) — expresses JavaScript's prototypal nature more directly than classes. It avoids the `new` keyword entirely and makes the prototype chain explicit.",
  "",
  "## Performance Implications of Prototype Chains",
  "",
  "Each prototype chain lookup has a cost. In V8, hidden classes (Maps) are associated not just with the object but with each prototype in the chain. Property access on an object with a deep prototype chain requires checking the hidden class at each level. V8's Inline Caches (ICs) optimize repeated property accesses, but deep chains increase the likelihood of cache misses and megamorphic access.",
  "",
  "The practical guidance:",
  "- **Keep prototype chains shallow.** 2-3 levels maximum (object → prototype → Object.prototype).",
  "- **Prefer own properties for hot data.** Properties accessed in tight loops should be own properties, not inherited.",
  "- **Avoid `__proto__` setter.** It forces dictionary-mode objects, eliminating all hidden class optimizations.",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **JavaScript has prototypal inheritance, not classical inheritance.** `class` is a veneer. Understanding `[[Prototype]]` is essential for debugging property resolution.",
  "2. **Favor composition over inheritance.** JavaScript's liberal object system makes mixins, factories, and composition patterns more natural than deep class hierarchies.",
  "3. **Use `Object.create(null)` for dictionary/map objects.** Objects with no prototype have no inherited properties (`toString`, `hasOwnProperty`) — safer for programmatic key-value stores.",
  "4. **Deep prototype chains hurt performance.** V8 optimizes monomorphic property access; deep chains push access toward megamorphic.",
]));

// ============================================================================
// fe-async — Async JavaScript
// ============================================================================
setContent("fe-async", md([
  "## Why This Matters",
  "",
  "JavaScript's async model — from callbacks through promises to async/await — is the foundation of every modern web application. It is how a single thread handles thousands of concurrent operations without blocking. Every data fetch, every user interaction, every animation depends on async patterns. Superficial understanding leads to race conditions, Promise chains that swallow errors, and callback patterns that are impossible to reason about. Deep understanding enables predictable, maintainable async code.",
  "",
  "## The Evolution: Callbacks",
  "",
  "The first async pattern in JavaScript was the **callback** — a function passed as an argument to be called when an operation completes:",
  "",
  "```javascript",
  "fs.readFile('data.json', (err, data) => {",
  "  if (err) return console.error(err);",
  "  parseJSON(data, (err, parsed) => {",
  "    if (err) return console.error(err);",
  "    queryDatabase(parsed.id, (err, result) => {",
  "      if (err) return console.error(err);",
  '      console.log("Result:", result);',
  "    });",
  "  });",
  "});",
  "```",
  "",
  "This pattern — the **callback pyramid of doom** — has three fundamental problems:",
  "1. **Error handling is manual and repetitive** — each callback must check for errors.",
  "2. **Composition is awkward** — running operations in parallel or with complex dependency chains requires manual coordination.",
  "3. **Control flow is implicit** — you cannot tell the execution order just by looking at the code structure.",
  "",
  "## Promises: Structured Async",
  "",
  "A Promise represents an eventual value (or error) that may not be available yet. It is a **container** for an asynchronous result. Promises have three states: `pending` (initial), `fulfilled` (resolved with a value), or `rejected` (resolved with an error). Once settled, a Promise's state is immutable — it cannot transition again.",
  "",
  "### The Power of `.then()`",
  "",
  "Every `.then()` call returns a **new Promise**, which enables flat, composable chains:",
  "",
  "```javascript",
  "fetch('/api/users')",
  "  .then(res => {",
  "    if (!res.ok) throw new Error(`HTTP ${res.status}`);",
  "    return res.json();",
  "  })",
  "  .then(users => fetch(`/api/roles?ids=${users.map(u => u.id)}`))",
  "  .then(res => res.json())",
  "  .then(roles => console.log('Users with roles:', roles))",
  "  .catch(err => console.error('Request failed:', err));",
  "```",
  "",
  "The key insight: **the return value of `.then()` determines what the chain waits for**. If you return a value, the next `.then()` receives it immediately. If you return a Promise, the next `.then()` waits for it to settle. This is what enables flat chaining instead of nested callbacks.",
  "",
  "### Parallel Execution Patterns",
  "",
  "| Method | Behavior | When to Use |",
  "|---|---|---",
  "| `Promise.all()` | Runs all promises in parallel, rejects if any rejects | When all results are needed and any failure is fatal |",
  "| `Promise.allSettled()` | Runs all, never rejects — returns results + statuses | When you need all results even if some fail |",
  "| `Promise.race()` | Settles with the first promise that settles | Timeouts: `Promise.race([fetch(url), timeout(5000)])` |",
  "| `Promise.any()` | Settles with the first **fulfilled**, rejects only if all reject | When you have multiple sources and only need one response |",
  "",
  "## async/await: Syntactic Sugar Over Promises",
  "",
  "The `async` and `await` keywords transformed Promise-based code into something that reads like synchronous code while remaining asynchronous:",
  "",
  "```javascript",
  "async function loadUserDashboard(userId) {",
  "  try {",
  "    const user = await fetchUser(userId);       // pauses, but doesn't block thread",
  "    const orders = await fetchOrders(user.id);  // next line waits for user",
  "    return { user, orders };",
  "  } catch (err) {",
  "    logger.error('Dashboard failed', { userId, error: err.message });",
  "    throw new Error('Unable to load dashboard');",
  "  }",
  "}",
  "```",
  "",
  "### What `await` Actually Does",
  "",
  "`await` does not block the thread. It **suspends** the execution of the async function, yielding control back to the event loop. The function's execution context is saved and will be restored when the awaited Promise settles. This is why an async function can \"wait\" for a network request without blocking other operations — the thread remains free to handle other events, render frames, and process other requests.",
  "",
  "### Error Handling in async/await",
  "",
  "One of the biggest advantages of async/await is that `try/catch` works natively. An unhandled rejection in an async function becomes a synchronous exception. However, there is a critical gotcha: **every async function must handle its own errors or return the promise to a caller that does**.",
  "",
  "```javascript",
  "// BAD: Fire-and-forget — error is silently swallowed",
  "async function saveUser(data) {",
  "  await db.save(data);  // if this throws, nobody catches it",
  "}",
  "saveUser({name: 'Alice'}); // promise not returned — error is lost",
  "",
  "// GOOD: Return the promise for the caller to handle",
  "async function saveUser(data) {",
  "  await db.save(data);",
  "}",
  "saveUser({name: 'Alice'}).catch(err => logger.error(err));",
  "",
  "// Or handle inside:",
  "async function saveUser(data) {",
  "  try {",
  "    await db.save(data);",
  "  } catch (err) {",
  "    logger.error(err);",
  "    throw err; // re-raise if caller needs to know",
  "  }",
  "}",
  "```",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Always handle Promise rejections.** Unhandled rejections will crash Node.js process in future versions. Use `process.on('unhandledRejection')` for global safety nets.",
  "2. **Prefer Promise.allSettled over Promise.all** for non-critical parallel operations. A single failure should not take down the entire batch unless the operation is a transaction.",
  "3. **Use async/await for sequential dependencies, Promise.all for parallel operations.** Mixing both patterns is the correct approach for most real-world scenarios.",
  "4. **Timeouts are essential.** Every external call should have a timeout: use `Promise.race([operation, timeout(n)])`.",
  "5. **ESLint `no-floating-promises` is non-negotiable.** Every Promise must be handled — either awaited, `.then()`'d, or `.catch()`'d.",
]));

// ============================================================================
// fe-modules — ES Modules vs CommonJS
// ============================================================================
setContent("fe-modules", md([
  "## Why This Matters",
  "",
  "The module system you choose — CommonJS or ES Modules — affects everything from code organization to bundle size to server startup time. It determines whether your bundler can eliminate unused code (tree-shaking), whether your dependencies load in parallel or sequentially, and whether Node.js can optimize module loading. As applications grow beyond a few files, the module system becomes the backbone of code architecture. Choosing the wrong one or mixing them incorrectly leads to subtle bugs, slow builds, and production errors.",
  "",
  "## CommonJS (CJS): The Node.js Original",
  "",
  "CommonJS was created by the Node.js community before JavaScript had a standard module system. It uses `require()` to import and `module.exports` to export:",
  "",
  "```javascript",
  "// math.js",
  "module.exports = { add: (a, b) => a + b };",
  "",
  "// main.js",
  "const math = require('./math');",
  "const result = math.add(1, 2);",
  "```",
  "",
  "### How CommonJS Works",
  "",
  "`require()` is **synchronous**. When Node.js encounters a `require('./math')` call, it:",
  "1. Resolves the file path (`math.js`)",
  "2. Reads the file from disk (synchronous I/O)",
  "3. Wraps it in a function: `(function(exports, require, module, __filename, __dirname) { ... })`",
  "4. Executes the wrapped function",
  "5. Caches the result in `require.cache` — subsequent `require('./math')` returns the cached exports",
  "",
  "Exports are a **plain object** (`module.exports`). When you assign `module.exports = { ... }`, you replace the object entirely. When you assign `exports.foo = 'bar'`, you're mutating the same object that `require()` returns. This is a common source of confusion: `exports = { ... }` does NOT work because it reassigns the local `exports` variable without affecting `module.exports`.",
  "",
  "CommonJS has two critical limitations:",
  "1. **No tree-shaking.** Because `require()` is a function call, the bundler cannot statically analyze which exports are used. When you write `const { add } = require('./math')`, the bundler must include the entire `math.js` file — it cannot remove unused exports.",
  "2. **Cannot be asynchronously loaded.** Synchronous `require()` is fine on the server (disk reads are fast), but it would block the browser's UI thread. This is why CommonJS never worked natively in browsers.",
  "",
  "## ES Modules (ESM): The Standard",
  "",
  "ES Modules are the official JavaScript module system defined in the ECMAScript specification. They use `import` and `export` declarations:",
  "",
  "```javascript",
  "// math.js",
  "export const add = (a, b) => a + b;",
  "export const subtract = (a, b) => a - b;",
  "",
  "// main.js",
  "import { add } from './math.js';  // note: .js extension is required in ESM",
  "console.log(add(1, 2));",
  "```",
  "",
  "### How ESM Works Differently",
  "",
  "ESM is fundamentally different from CommonJS in three ways:",
  "",
  "1. **Static structure.** `import` and `export` are keywords, not function calls. They are resolved at **parse time**, before any code executes. This is not an implementation detail — it is a language guarantee. The static structure enables optimizations that CJS cannot achieve.",
  "",
  "2. **Live bindings.** ESM exports are **live references**, not copies. When a module exports a variable, importing modules see the current value, not the value at import time. If the exporting module mutates the variable, all importers see the change (though mutation of exported bindings is considered bad practice — prefer `const` exports).",
  "",
  "3. **Asynchronous loading.** ESM modules are fetched and parsed asynchronously. The browser (or Node.js) can construct the entire dependency graph before executing any module, enabling parallel loading across the graph.",
  "",
  "### Tree-Shaking: The Killer Feature",
  "",
  "Because `import` is static, a bundler like Rollup, Webpack, or Vite can analyze exactly which exports are imported and eliminate the rest. This is **tree-shaking**:",
  "",
  "```javascript",
  "// Suppose this module exports 20 utility functions",
  "import { onlyFunction } from './huge-library.js';",
  "// The bundler can prove that only one function is used",
  "// and eliminate the other 19 from the bundle",
  "```",
  "",
  "This is impossible with CommonJS because `require('./huge-library')` is a function call whose result cannot be statically analyzed. In modern frontend development, **tree-shaking is the primary reason to choose ESM over CJS**. The difference in bundle size can be dramatic — a 200KB library may tree-shake down to 5KB when only one function is imported.",
  "",
  "## Interoperability: Mixing CJS and ESM",
  "",
  "In practice, Node.js and bundlers need to handle mixed ecosystems. The rules:",
  "",
  "1. **ESM can `import` CJS modules.** The CJS module's `module.exports` becomes the default export of the ESM import. Named exports may not be detected reliably.",
  "2. **CJS cannot `require()` ESM modules.** `require()` is synchronous, but ESM modules may have asynchronous top-level execution. You must use `import()` (dynamic import) instead.",
  "3. **`import()` (dynamic import) works in both systems.** It returns a Promise and can load any module type.",
  "",
  "```javascript",
  "// Inside an ESM file, importing a CJS module:",
  "import fs from 'fs';       // default import — works",
  "import { readFile } from 'fs';  // named import — may or may not work",
  "",
  "// Inside a CJS file, importing an ESM module:",
  "const mod = await import('./esm-module.js');  // dynamic import — works",
  "// const mod = require('./esm-module.js');    // ERROR: cannot require ESM",
  "```",
  "",
  "## Package.json Configuration",
  "",
  "Node.js determines which module system a file uses based on its `package.json`:",
  "",
  "- If `\"type\": \"module\"` is set, all `.js` files in the package are treated as ESM.",
  "- If `\"type\": \"commonjs\"` (or no `type` field), `.js` files are treated as CJS.",
  "- `.mjs` files are always ESM, `.cjs` files are always CJS.",
  "",
  "```json",
  "// package.json",
  "{",
  "  \"type\": \"module\",  // all .js files are ESM in this package",
  "  \"exports\": {",
  "    \".\": \"./dist/index.js\",",
  "    \"./utils\": \"./dist/utils.js\"",
  "  }",
  "}",
  "```",
  "",
  "## CTO-Level Takeaways",
  "",
  "1. **Use ESM for new projects.** Tree-shaking, static analysis, and browser-native support make ESM the clear choice. CJS should be considered legacy.",
  "2. **Set `\"type\": \"module\"` in package.json.** This makes all `.js` files ESM by default. Use `.cjs` extension for the rare files that need CommonJS.",
  "3. **Use `exports` in package.json** to define a clean public API surface. This prevents importing internal modules that should not be exposed.",
  "4. **Be careful with mixed CJS/ESM dependencies.** Libraries that export CJS are consumed differently than ESM ones. Check the `module` or `exports` field in the library's package.json.",
  "5. **Tree-shaking is a package-level optimization.** It works best when your dependencies are also written as ESM. Prefer libraries that ship ESM (marked by `\"type\": \"module\"` or `.mjs` extension).",
]));

fs.writeFileSync(srcPath, src, "utf8");
console.log("All topics done!");
